var Module = (() => {
  var _scriptName = import.meta.url;
  
  return (
async function(moduleArg = {}) {
  var moduleRtn;

var f=moduleArg,aa,ba,ca=new Promise((a,b)=>{aa=a;ba=b}),da="object"==typeof window,ea="undefined"!=typeof WorkerGlobalScope,fa="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type;if(fa){const {createRequire:a}=await import("module");var require=a("/")}var ha=Object.assign({},f),ia=(a,b)=>{throw b;},l="",ja,ka;
if(fa){var fs=require("fs"),la=require("path");import.meta.url.startsWith("data:")||(l=la.dirname(require("url").fileURLToPath(import.meta.url))+"/");ka=a=>{a=ma(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=ma(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.slice(2);ia=(a,b)=>{process.exitCode=a;throw b;}}else if(da||ea)ea?l=self.location.href:"undefined"!=typeof document&&document.currentScript&&(l=document.currentScript.src),_scriptName&&(l=_scriptName),
l.startsWith("blob:")?l="":l=l.substr(0,l.replace(/[?#].*/,"").lastIndexOf("/")+1),ea&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ja=async a=>{if(ma(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();
throw Error(b.status+" : "+b.url);};var na=f.print||console.log.bind(console),q=f.printErr||console.error.bind(console);Object.assign(f,ha);ha=null;var oa=f.wasmBinary,pa,qa=!1,ra,t,y,sa,ta,ua,z,va,wa,xa,ya,za=a=>a.startsWith("data:application/octet-stream;base64,"),ma=a=>a.startsWith("file://");
function Aa(){var a=pa.buffer;f.HEAP8=t=new Int8Array(a);f.HEAP16=sa=new Int16Array(a);f.HEAPU8=y=new Uint8Array(a);f.HEAPU16=ta=new Uint16Array(a);f.HEAP32=ua=new Int32Array(a);f.HEAPU32=z=new Uint32Array(a);f.HEAPF32=va=new Float32Array(a);f.HEAPF64=ya=new Float64Array(a);f.HEAP64=wa=new BigInt64Array(a);f.HEAPU64=xa=new BigUint64Array(a)}var Ba=[],Ca=[],Da=[];function Ea(){var a=f.preRun.shift();Ba.unshift(a)}var C=0,Fa=null;function Ga(){C++;f.monitorRunDependencies?.(C)}
function Ha(){C--;f.monitorRunDependencies?.(C);if(0==C&&Fa){var a=Fa;Fa=null;a()}}function Ia(a){f.onAbort?.(a);a="Aborted("+a+")";q(a);qa=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}var Ja;async function Ka(a){if(!oa)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==Ja&&oa)a=new Uint8Array(oa);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}
async function La(a,b){try{var c=await Ka(a);return await WebAssembly.instantiate(c,b)}catch(d){q(`failed to asynchronously prepare wasm: ${d}`),Ia(d)}}async function Ma(a){var b=Ja;if(!(oa||"function"!=typeof WebAssembly.instantiateStreaming||za(b)||ma(b)||fa))try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){q(`wasm streaming compile failed: ${d}`),q("falling back to ArrayBuffer instantiation")}return La(b,a)}
class Na{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Oa=a=>{for(;0<a.length;)a.shift()(f)},Pa=f.noExitRuntime||!0,Qa="undefined"!=typeof TextDecoder?new TextDecoder:void 0,D=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Qa)return Qa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>
10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Ra=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a},Sa,F=a=>{for(var b="";y[a];)b+=Sa[y[a++]];return b},G={},H={},Ta={},I,Ua=a=>{throw new I(a);},Va,K=(a,b,c)=>{function d(k){k=c(k);if(k.length!==a.length)throw new Va("Mismatched type converter count");for(var n=0;n<a.length;++n)J(a[n],k[n])}a.forEach(k=>Ta[k]=b);var e=Array(b.length),g=[],h=0;b.forEach((k,n)=>{H.hasOwnProperty(k)?
e[n]=H[k]:(g.push(k),G.hasOwnProperty(k)||(G[k]=[]),G[k].push(()=>{e[n]=H[k];++h;h===g.length&&d(e)}))});0===g.length&&d(e)};function Wa(a,b,c={}){var d=b.name;if(!a)throw new I(`type "${d}" must have a positive integer typeid pointer`);if(H.hasOwnProperty(a)){if(c.sb)return;throw new I(`Cannot register type '${d}' twice`);}H[a]=b;delete Ta[a];G.hasOwnProperty(a)&&(b=G[a],delete G[a],b.forEach(e=>e()))}function J(a,b,c={}){return Wa(a,b,c)}
var Xa=(a,b,c)=>{switch(b){case 1:return c?d=>t[d]:d=>y[d];case 2:return c?d=>sa[d>>1]:d=>ta[d>>1];case 4:return c?d=>ua[d>>2]:d=>z[d>>2];case 8:return c?d=>wa[d>>3]:d=>xa[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Ya=a=>{throw new I(a.G.O.K.name+" instance already deleted");},Za=!1,$a=()=>{},ab=(a,b,c)=>{if(b===c)return a;if(void 0===c.S)return null;a=ab(a,b,c.S);return null===a?null:c.kb(a)},bb={},cb={},db=(a,b)=>{if(void 0===b)throw new I("ptr should not be undefined");
for(;a.S;)b=a.ta(b),a=a.S;return cb[b]},fb=(a,b)=>{if(!b.O||!b.L)throw new Va("makeClassHandle requires ptr and ptrType");if(!!b.V!==!!b.R)throw new Va("Both smartPtrType and smartPtr must be specified");b.count={value:1};return eb(Object.create(a,{G:{value:b,writable:!0}}))},eb=a=>{if("undefined"===typeof FinalizationRegistry)return eb=b=>b,a;Za=new FinalizationRegistry(b=>{b=b.G;--b.count.value;0===b.count.value&&(b.R?b.V.ga(b.R):b.O.K.ga(b.L))});eb=b=>{var c=b.G;c.R&&Za.register(b,{G:c},b);return b};
$a=b=>{Za.unregister(b)};return eb(a)},gb=[];function hb(){}
var ib=(a,b)=>Object.defineProperty(b,"name",{value:a}),jb=(a,b,c)=>{if(void 0===a[b].P){var d=a[b];a[b]=function(...e){if(!a[b].P.hasOwnProperty(e.length))throw new I(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].P})!`);return a[b].P[e.length].apply(this,e)};a[b].P=[];a[b].P[d.oa]=d}},kb=(a,b,c)=>{if(f.hasOwnProperty(a)){if(void 0===c||void 0!==f[a].P&&void 0!==f[a].P[c])throw new I(`Cannot register public name '${a}' twice`);jb(f,a,a);if(f[a].P.hasOwnProperty(c))throw new I(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
f[a].P[c]=b}else f[a]=b,f[a].oa=c},lb=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function mb(a,b,c,d,e,g,h,k){this.name=a;this.constructor=b;this.ka=c;this.ga=d;this.S=e;this.nb=g;this.ta=h;this.kb=k;this.yb=[]}var nb=(a,b,c)=>{for(;b!==c;){if(!b.ta)throw new I(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.ta(a);b=b.S}return a};
function ob(a,b){if(null===b){if(this.Da)throw new I(`null is not a valid ${this.name}`);return 0}if(!b.G)throw new I(`Cannot pass "${Ra(b)}" as a ${this.name}`);if(!b.G.L)throw new I(`Cannot pass deleted object as a pointer of type ${this.name}`);return nb(b.G.L,b.G.O.K,this.K)}
function pb(a,b){if(null===b){if(this.Da)throw new I(`null is not a valid ${this.name}`);if(this.wa){var c=this.zb();null!==a&&a.push(this.ga,c);return c}return 0}if(!b||!b.G)throw new I(`Cannot pass "${Ra(b)}" as a ${this.name}`);if(!b.G.L)throw new I(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.va&&b.G.O.va)throw new I(`Cannot convert argument of type ${b.G.V?b.G.V.name:b.G.O.name} to parameter type ${this.name}`);c=nb(b.G.L,b.G.O.K,this.K);if(this.wa){if(void 0===b.G.R)throw new I("Passing raw pointer to smart pointer is illegal");
switch(this.Bb){case 0:if(b.G.V===this)c=b.G.R;else throw new I(`Cannot convert argument of type ${b.G.V?b.G.V.name:b.G.O.name} to parameter type ${this.name}`);break;case 1:c=b.G.R;break;case 2:if(b.G.V===this)c=b.G.R;else{var d=b.clone();c=this.Ab(c,qb(()=>d["delete"]()));null!==a&&a.push(this.ga,c)}break;default:throw new I("Unsupporting sharing policy");}}return c}
function rb(a,b){if(null===b){if(this.Da)throw new I(`null is not a valid ${this.name}`);return 0}if(!b.G)throw new I(`Cannot pass "${Ra(b)}" as a ${this.name}`);if(!b.G.L)throw new I(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.G.O.va)throw new I(`Cannot convert argument of type ${b.G.O.name} to parameter type ${this.name}`);return nb(b.G.L,b.G.O.K,this.K)}function sb(a){return this.fromWireType(z[a>>2])}
function tb(a,b,c,d,e,g,h,k,n,p,m){this.name=a;this.K=b;this.Da=c;this.va=d;this.wa=e;this.xb=g;this.Bb=h;this.Xa=k;this.zb=n;this.Ab=p;this.ga=m;e||void 0!==b.S?this.toWireType=pb:(this.toWireType=d?ob:rb,this.W=null)}
var ub=(a,b,c)=>{if(!f.hasOwnProperty(a))throw new Va("Replacing nonexistent public symbol");void 0!==f[a].P&&void 0!==c?f[a].P[c]=b:(f[a]=b,f[a].oa=c)},vb,L=(a,b)=>{a=F(a);var c=vb.get(b);if("function"!=typeof c)throw new I(`unknown function pointer with signature ${a}: ${b}`);return c},wb,yb=a=>{a=xb(a);var b=F(a);N(a);return b},zb=(a,b)=>{function c(g){e[g]||H[g]||(Ta[g]?Ta[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};b.forEach(c);throw new wb(`${a}: `+d.map(yb).join([", "]));},Ab=(a,b)=>{for(var c=
[],d=0;d<a;d++)c.push(z[b+4*d>>2]);return c},Bb=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function Cb(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].W)return!0;return!1}function Db(a){var b=Function;if(!(b instanceof Function))throw new TypeError(`new_ called with constructor type ${typeof b} which is not a function`);var c=ib(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Eb(a,b,c,d,e,g){var h=b.length;if(2>h)throw new I("argTypes array size mismatch! Must at least get return value and 'this' types!");var k=null!==b[1]&&null!==c,n=Cb(b);c="void"!==b[0].name;d=[a,Ua,d,e,Bb,b[0],b[1]];for(e=0;e<h-2;++e)d.push(b[e+2]);if(!n)for(e=k?1:2;e<b.length;++e)null!==b[e].W&&d.push(b[e].W);n=Cb(b);e=b.length-2;var p=[],m=["fn"];k&&m.push("thisWired");for(h=0;h<e;++h)p.push(`arg${h}`),m.push(`arg${h}Wired`);p=p.join(",");m=m.join(",");p=`return function (${p}) {\n`;n&&
(p+="var destructors = [];\n");var r=n?"destructors":"null",v="humanName throwBindingError invoker fn runDestructors retType classParam".split(" ");k&&(p+=`var thisWired = classParam['toWireType'](${r}, this);\n`);for(h=0;h<e;++h)p+=`var arg${h}Wired = argType${h}['toWireType'](${r}, arg${h});\n`,v.push(`argType${h}`);p+=(c||g?"var rv = ":"")+`invoker(${m});\n`;if(n)p+="runDestructors(destructors);\n";else for(h=k?1:2;h<b.length;++h)g=1===h?"thisWired":"arg"+(h-2)+"Wired",null!==b[h].W&&(p+=`${g}_dtor(${g});\n`,
v.push(`${g}_dtor`));c&&(p+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");let [x,u]=[v,p+"}\n"];x.push(u);b=Db(x)(...d);return ib(a,b)}
var Fb=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?a.substr(0,b):a},Gb=[],O=[],Hb=a=>{9<a&&0===--O[a+1]&&(O[a]=void 0,Gb.push(a))},qb=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Gb.pop()||O.length;O[b]=a;O[b+1]=1;return b}},Ib={name:"emscripten::val",fromWireType:a=>{if(!a)throw new I("Cannot use deleted val. handle = "+a);var b=O[a];Hb(a);return b},toWireType:(a,b)=>qb(b),ba:8,readValueFromPointer:sb,W:null},Jb=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(va[c>>
2])};case 8:return function(c){return this.fromWireType(ya[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Kb=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var k=a.charCodeAt(++g);h=65536+((h&1023)<<10)|k&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=
128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e},Lb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Mb="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,Nb=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&ta[c];)++c;c<<=1;if(32<c-a&&Mb)return Mb.decode(y.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=sa[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},Ob=(a,b,c)=>{c??=2147483647;if(2>c)return 0;
c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)sa[b>>1]=a.charCodeAt(e),b+=2;sa[b>>1]=0;return b-d},Pb=a=>2*a.length,Qb=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=ua[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},Rb=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=g&&57343>=g){var h=a.charCodeAt(++e);g=65536+((g&1023)<<10)|h&1023}ua[b>>
2]=g;b+=4;if(b+4>c)break}ua[b>>2]=0;return b-d},Sb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},Tb=0,Ub={},Vb=a=>{ra=a;Pa||0<Tb||(f.onExit?.(a),qa=!0);ia(a,new Na(a))},Wb=a=>{if(!qa)try{if(a(),!(Pa||0<Tb))try{ra=a=ra,Vb(a)}catch(b){b instanceof Na||"unwind"==b||ia(1,b)}}catch(b){b instanceof Na||"unwind"==b||ia(1,b)}},Xb=()=>{if(fa){var a=require("crypto");return b=>a.randomFillSync(b)}return b=>crypto.getRandomValues(b)},Yb=a=>{(Yb=Xb())(a)},Zb=
(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},P=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Zb(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},ac=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},Q=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],
bc=(a,b)=>P(a+"/"+b),cc=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:R.cwd();if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Zb(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},dc=(a,b)=>{function c(h){for(var k=0;k<h.length&&""===h[k];k++);for(var n=h.length-1;0<=n&&""===h[n];n--);return k>n?[]:h.slice(k,n-k+1)}a=cc(a).substr(1);b=cc(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));
for(var d=Math.min(a.length,b.length),e=d,g=0;g<d;g++)if(a[g]!==b[g]){e=g;break}d=[];for(g=e;g<a.length;g++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},ec=[];function fc(a){var b=Array(Lb(a)+1);a=Kb(a,b,0,b.length);b.length=a;return b}var gc=[];function hc(a,b){gc[a]={input:[],output:[],ma:b};ic(a,jc)}
var jc={open(a){var b=gc[a.node.rdev];if(!b)throw new R.F(43);a.tty=b;a.seekable=!1},close(a){a.tty.ma.fsync(a.tty)},fsync(a){a.tty.ma.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.ma.Sa)throw new R.F(60);for(var e=0,g=0;g<d;g++){try{var h=a.tty.ma.Sa(a.tty)}catch(k){throw new R.F(29);}if(void 0===h&&0===e)throw new R.F(6);if(null===h||void 0===h)break;e++;b[c+g]=h}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.ma.Ga)throw new R.F(60);try{for(var e=0;e<d;e++)a.tty.ma.Ga(a.tty,
b[c+e])}catch(g){throw new R.F(29);}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},kc={Sa(){a:{if(!ec.length){var a=null;if(fa){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}ec=fc(a)}a=ec.shift()}return a},Ga(a,b){null===b||10===
b?(na(D(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(na(D(a.output)),a.output=[])},Ub(){return{Jb:25856,Lb:5,Ib:191,Kb:35387,Hb:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Vb(){return 0},Wb(){return[24,80]}},lc={Ga(a,b){null===b||10===b?(q(D(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(q(D(a.output)),a.output=[])}};
function mc(a,b){var c=a.J?a.J.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.J,a.J=new Uint8Array(b),0<a.M&&a.J.set(c.subarray(0,a.M),0))}
var S={$:null,N(){return S.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||R.isFIFO(c))throw new R.F(63);S.$||(S.$={dir:{node:{ea:S.H.ea,U:S.H.U,lookup:S.H.lookup,fa:S.H.fa,rename:S.H.rename,unlink:S.H.unlink,rmdir:S.H.rmdir,readdir:S.H.readdir,symlink:S.H.symlink},stream:{T:S.I.T}},file:{node:{ea:S.H.ea,U:S.H.U},stream:{T:S.I.T,read:S.I.read,write:S.I.write,na:S.I.na,la:S.I.la,ra:S.I.ra}},link:{node:{ea:S.H.ea,U:S.H.U,readlink:S.H.readlink},stream:{}},La:{node:{ea:S.H.ea,
U:S.H.U},stream:R.gb}});c=R.createNode(a,b,c,d);T(c.mode)?(c.H=S.$.dir.node,c.I=S.$.dir.stream,c.J={}):R.isFile(c.mode)?(c.H=S.$.file.node,c.I=S.$.file.stream,c.M=0,c.J=null):40960===(c.mode&61440)?(c.H=S.$.link.node,c.I=S.$.link.stream):8192===(c.mode&61440)&&(c.H=S.$.La.node,c.I=S.$.La.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.J[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},Tb(a){return a.J?a.J.subarray?a.J.subarray(0,a.M):new Uint8Array(a.J):new Uint8Array(0)},H:{ea(a){var b={};b.dev=
8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;T(a.mode)?b.size=4096:R.isFile(a.mode)?b.size=a.M:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},U(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.M!=b&&(0==b?(a.J=null,a.M=0):(c=a.J,a.J=new Uint8Array(b),c&&
a.J.set(c.subarray(0,Math.min(b,a.M))),a.M=b)))},lookup(){throw S.Ra;},fa(a,b,c,d){return S.createNode(a,b,c,d)},rename(a,b,c){try{var d=V(b,c)}catch(g){}if(d){if(T(a.mode))for(var e in d.J)throw new R.F(55);nc(d)}delete a.parent.J[a.name];b.J[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.J[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=V(a,b),d;for(d in c.J)throw new R.F(55);delete a.J[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.J)]},
symlink(a,b,c){a=S.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new R.F(28);return a.link}},I:{read(a,b,c,d,e){var g=a.node.J;if(e>=a.node.M)return 0;a=Math.min(a.node.M-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write(a,b,c,d,e,g){b.buffer===t.buffer&&(g=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.J||a.J.subarray)){if(g)return a.J=b.subarray(c,c+d),a.M=d;if(0===a.M&&0===e)return a.J=
b.slice(c,c+d),a.M=d;if(e+d<=a.M)return a.J.set(b.subarray(c,c+d),e),d}mc(a,e+d);if(a.J.subarray&&b.subarray)a.J.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.J[e+g]=b[c+g];a.M=Math.max(a.M,e+d);return d},T(a,b,c){1===c?b+=a.position:2===c&&R.isFile(a.node.mode)&&(b+=a.node.M);if(0>b)throw new R.F(28);return b},na(a,b,c){mc(a.node,b+c);a.node.M=Math.max(a.node.M,b+c)},la(a,b,c,d,e){if(!R.isFile(a.node.mode))throw new R.F(43);a=a.node.J;if(e&2||!a||a.buffer!==t.buffer){d=!0;Ia();e=void 0;if(!e)throw new R.F(48);
if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);t.set(a,e)}}else d=!1,e=a.byteOffset;return{L:e,Db:d}},ra(a,b,c,d){S.I.write(a,b,0,d,c,!1);return 0}}},oc=async a=>{a=await ja(a);return new Uint8Array(a)},pc=f.preloadPlugins||[],rc=(a,b,c,d)=>{"undefined"!=typeof Browser&&qc();var e=!1;pc.forEach(g=>{!e&&g.canHandle(b)&&(g.handle(a,b,c,d),e=!0)});return e},sc=(a,b,c,d,e,g,h,k,n,p)=>{function m(x){function u(w){p?.();k||R.Aa(a,b,w,d,e,n);g?.();Ha(v)}rc(x,
r,u,()=>{h?.();Ha(v)})||u(x)}var r=b?cc(P(a+"/"+b)):a,v=`cp ${r}`;Ga(v);"string"==typeof c?oc(c).then(m,h):m(c)},tc=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c};
function qc(){var a,b,c;R.Ca=!0;a??=f.stdin;b??=f.stdout;c??=f.stderr;a?R.da("/dev","stdin",a):R.symlink("/dev/tty","/dev/stdin");b?R.da("/dev","stdout",null,b):R.symlink("/dev/tty","/dev/stdout");c?R.da("/dev","stderr",null,c):R.symlink("/dev/tty1","/dev/stderr");R.open("/dev/stdin",0);R.open("/dev/stdout",1);R.open("/dev/stderr",1)}function ic(a,b){R.Qa[a]={I:b}}function T(a){return 16384===(a&61440)}
function V(a,b){var c=T(a.mode)?(c=W(a,"x"))?c:a.H.lookup?0:2:54;if(c)throw new R.F(c);for(c=R.Z[uc(a.id,b)];c;c=c.ja){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return R.lookup(a,b)}function nc(a){var b=uc(a.parent.id,a.name);if(R.Z[b]===a)R.Z[b]=a.ja;else for(b=R.Z[b];b;){if(b.ja===a){b.ja=a.ja;break}b=b.ja}}
function X(a,b={}){if(!a)throw new R.F(44);b.ua??(b.ua=!0);"/"===a.charAt(0)||(a=R.cwd()+"/"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(k=>!!k);for(var d=R.root,e="/",g=0;g<a.length;g++){var h=g===a.length-1;if(h&&b.parent)break;if("."!==a[g])if(".."===a[g])e=ac(e),d=d.parent;else{e=P(e+"/"+a[g]);try{d=V(d,a[g])}catch(k){if(44===k?.Ba&&h&&b.vb)return{path:e};throw k;}!d.Y||h&&!b.ua||(d=d.Y.root);if(40960===(d.mode&61440)&&(!h||b.X)){if(!d.H.readlink)throw new R.F(52);d=d.H.readlink(d);"/"===
d.charAt(0)||(d=ac(e)+"/"+d);a=d+"/"+a.slice(g+1).join("/");continue a}}}return{path:e,node:d}}throw new R.F(32);}function Y(a){for(var b;;){if(R.Va(a))return a=a.N.Wa,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function uc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%R.Z.length}function vc(a){var b=uc(a.parent.id,a.name);a.ja=R.Z[b];R.Z[b]=a}function wc(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function W(a,b){if(R.Ta)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function xc(a,b){if(!T(a.mode))return 54;try{return V(a,b),20}catch(c){}return W(a,"wx")}function yc(a,b,c){try{var d=V(a,b)}catch(e){return e.Ba}if(a=W(a,"wx"))return a;if(c){if(!T(d.mode))return 54;if(R.Va(d)||Y(d)===R.cwd())return 10}else if(T(d.mode))return 31;return 0}function zc(a,b){if(!a)throw new R.F(b);return a}
function Ac(a){a=R.qb(a);if(!a)throw new R.F(8);return a}function Bc(a,b=-1){a=Object.assign(new R.bb,a);if(-1==b)a:{for(b=0;b<=R.eb;b++)if(!R.streams[b])break a;throw new R.F(33);}a.fd=b;return R.streams[b]=a}function Cc(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.qa)}return b}function Dc(a,b,c){"undefined"==typeof c&&(c=b,b=438);return R.fa(a,b|8192,c)}function Ec(a,b,c,d){a="string"==typeof a?a:Y(a);b=P(a+"/"+b);return R.create(b,tc(c,d))}
function Fc(a){if(!(a.tb||a.ub||a.link||a.J)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");try{a.J=ka(a.url),a.M=a.J.length}catch(b){throw new R.F(29);}}}
var R={root:null,qa:[],Qa:{},streams:[],Fa:1,Z:null,Oa:"/",Ca:!1,Ta:!0,F:class{name="ErrnoError";constructor(a){this.Ba=a}},mb:null,xa:0,Ya:{},bb:class{aa={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.aa.flags}set flags(a){this.aa.flags=a}get position(){return this.aa.position}set position(a){this.aa.position=a}},ab:class{H={};I={};Y=null;constructor(a,b,c,d){a||=this;this.parent=a;this.N=a.N;this.id=R.Fa++;this.name=b;this.mode=c;this.rdev=d;this.atime=
this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get ub(){return T(this.mode)}get tb(){return 8192===(this.mode&61440)}},createNode(a,b,c,d){a=new R.ab(a,b,c,d);vc(a);return a},Va(a){return a===a.parent},isFile(a){return 32768===(a&61440)},isFIFO(a){return 4096===(a&61440)},isSocket(a){return 49152===(a&49152)},eb:4096,qb:a=>R.streams[a],Nb(a,
b=-1){a=Bc(a,b);a.I?.Mb?.(a);return a},gb:{open(a){a.I=R.ob(a.node.rdev).I;a.I.open?.(a)},T(){throw new R.F(70);}},Ea:a=>a>>8,Yb:a=>a&255,ia:(a,b)=>a<<8|b,ob:a=>R.Qa[a],$a(a,b){function c(h){R.xa--;return b(h)}function d(h){if(h){if(!d.lb)return d.lb=!0,c(h)}else++g>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);R.xa++;1<R.xa&&q(`warning: ${R.xa} FS.syncfs operations in flight at once, probably just doing extra work`);var e=Cc(R.root.N),g=0;e.forEach(h=>{if(!h.type.$a)return d(null);h.type.$a(h,
a,d)})},N(a,b,c){var d="/"===c;if(d&&R.root)throw new R.F(10);if(!d&&c){var e=X(c,{ua:!1});c=e.path;e=e.node;if(e.Y)throw new R.F(10);if(!T(e.mode))throw new R.F(54);}b={type:a,wb:b,Wa:c,qa:[]};a=a.N(b);a.N=b;b.root=a;d?R.root=a:e&&(e.Y=b,e.N&&e.N.qa.push(b));return a},cc(a){a=X(a,{ua:!1});if(!a.node.Y)throw new R.F(28);a=a.node;var b=a.Y,c=Cc(b);Object.keys(R.Z).forEach(d=>{for(d=R.Z[d];d;){var e=d.ja;c.includes(d.N)&&nc(d);d=e}});a.Y=null;a.N.qa.splice(a.N.qa.indexOf(b),1)},lookup(a,b){return a.H.lookup(a,
b)},fa(a,b,c){var d=X(a,{parent:!0}).node;a=Q(a);if(!a)throw new R.F(28);if("."===a||".."===a)throw new R.F(20);var e=xc(d,a);if(e)throw new R.F(e);if(!d.H.fa)throw new R.F(63);return d.H.fa(d,a,b,c)},Za(a){var b={Gb:4096,Qb:4096,blocks:1E6,Fb:5E5,Eb:5E5,files:R.Fa,Ob:R.Fa-1,Rb:42,flags:2,$b:255};a=X(a,{X:!0}).node;a?.H.Za&&Object.assign(b,a.H.Za(a.N.wb.root));return b},create(a,b=438){return R.fa(a,b&4095|32768,0)},mkdir(a,b=511){return R.fa(a,b&1023|16384,0)},Zb(a,b){a=a.split("/");for(var c="",
d=0;d<a.length;++d)if(a[d]){c+="/"+a[d];try{R.mkdir(c,b)}catch(e){if(20!=e.Ba)throw e;}}},symlink(a,b){if(!cc(a))throw new R.F(44);var c=X(b,{parent:!0}).node;if(!c)throw new R.F(44);b=Q(b);var d=xc(c,b);if(d)throw new R.F(d);if(!c.H.symlink)throw new R.F(63);return c.H.symlink(c,b,a)},rename(a,b){var c=ac(a),d=ac(b),e=Q(a),g=Q(b);var h=X(a,{parent:!0});var k=h.node;h=X(b,{parent:!0});h=h.node;if(!k||!h)throw new R.F(44);if(k.N!==h.N)throw new R.F(75);var n=V(k,e);a=dc(a,d);if("."!==a.charAt(0))throw new R.F(28);
a=dc(b,c);if("."!==a.charAt(0))throw new R.F(55);try{var p=V(h,g)}catch(m){}if(n!==p){b=T(n.mode);if(e=yc(k,e,b))throw new R.F(e);if(e=p?yc(h,g,b):xc(h,g))throw new R.F(e);if(!k.H.rename)throw new R.F(63);if(n.Y||p&&p.Y)throw new R.F(10);if(h!==k&&(e=W(k,"w")))throw new R.F(e);nc(n);try{k.H.rename(n,h,g),n.parent=h}catch(m){throw m;}finally{vc(n)}}},rmdir(a){var b=X(a,{parent:!0}).node;a=Q(a);var c=V(b,a),d=yc(b,a,!0);if(d)throw new R.F(d);if(!b.H.rmdir)throw new R.F(63);if(c.Y)throw new R.F(10);
b.H.rmdir(b,a);nc(c)},readdir(a){a=X(a,{X:!0}).node;return zc(a.H.readdir,54)(a)},unlink(a){var b=X(a,{parent:!0}).node;if(!b)throw new R.F(44);a=Q(a);var c=V(b,a),d=yc(b,a,!1);if(d)throw new R.F(d);if(!b.H.unlink)throw new R.F(63);if(c.Y)throw new R.F(10);b.H.unlink(b,a);nc(c)},readlink(a){a=X(a).node;if(!a)throw new R.F(44);if(!a.H.readlink)throw new R.F(28);return a.H.readlink(a)},stat(a,b){a=X(a,{X:!b}).node;return zc(a.H.ea,63)(a)},lstat(a){return R.stat(a,!0)},chmod(a,b,c){a="string"==typeof a?
X(a,{X:!c}).node:a;zc(a.H.U,63)(a,{mode:b&4095|a.mode&-4096,ctime:Date.now(),jb:c})},lchmod(a,b){R.chmod(a,b,!0)},fchmod(a,b){a=Ac(a);R.chmod(a.node,b)},chown(a,b,c,d){a="string"==typeof a?X(a,{X:!d}).node:a;zc(a.H.U,63)(a,{timestamp:Date.now(),jb:d})},lchown(a,b,c){R.chown(a,b,c,!0)},fchown(a,b,c){a=Ac(a);R.chown(a.node,b,c)},truncate(a,b){if(0>b)throw new R.F(28);a="string"==typeof a?X(a,{X:!0}).node:a;if(T(a.mode))throw new R.F(31);if(!R.isFile(a.mode))throw new R.F(28);var c=W(a,"w");if(c)throw new R.F(c);
zc(a.H.U,63)(a,{size:b,timestamp:Date.now()})},Sb(a,b){a=Ac(a);if(0===(a.flags&2097155))throw new R.F(28);R.truncate(a.node,b)},dc(a,b,c){a=X(a,{X:!0}).node;zc(a.H.U,63)(a,{atime:b,mtime:c})},open(a,b,c=438){if(""===a)throw new R.F(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");a=X(a,{X:!(b&131072),vb:!0});d=a.node;a=
a.path}var g=!1;if(b&64)if(d){if(b&128)throw new R.F(20);}else{if(e)throw new R.F(31);d=R.fa(a,c|511,0);g=!0}if(!d)throw new R.F(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&!T(d.mode))throw new R.F(54);if(!g&&(e=d?40960===(d.mode&61440)?32:T(d.mode)&&("r"!==wc(b)||b&576)?31:W(d,wc(b)):44))throw new R.F(e);b&512&&!g&&R.truncate(d,0);b&=-131713;e=Bc({node:d,path:Y(d),flags:b,seekable:!0,position:0,I:d.I,Cb:[],error:!1});e.I.open&&e.I.open(e);g&&R.chmod(d,c&511);!f.logReadFiles||b&1||a in R.Ya||
(R.Ya[a]=1);return e},close(a){if(null===a.fd)throw new R.F(8);a.rb&&(a.rb=null);try{a.I.close&&a.I.close(a)}catch(b){throw b;}finally{R.streams[a.fd]=null}a.fd=null},T(a,b,c){if(null===a.fd)throw new R.F(8);if(!a.seekable||!a.I.T)throw new R.F(70);if(0!=c&&1!=c&&2!=c)throw new R.F(28);a.position=a.I.T(a,b,c);a.Cb=[];return a.position},read(a,b,c,d,e){if(0>d||0>e)throw new R.F(28);if(null===a.fd)throw new R.F(8);if(1===(a.flags&2097155))throw new R.F(8);if(T(a.node.mode))throw new R.F(31);if(!a.I.read)throw new R.F(28);
var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new R.F(70);b=a.I.read(a,b,c,d,e);g||(a.position+=b);return b},write(a,b,c,d,e,g){if(0>d||0>e)throw new R.F(28);if(null===a.fd)throw new R.F(8);if(0===(a.flags&2097155))throw new R.F(8);if(T(a.node.mode))throw new R.F(31);if(!a.I.write)throw new R.F(28);a.seekable&&a.flags&1024&&R.T(a,0,2);var h="undefined"!=typeof e;if(!h)e=a.position;else if(!a.seekable)throw new R.F(70);b=a.I.write(a,b,c,d,e,g);h||(a.position+=b);return b},
na(a,b,c){if(null===a.fd)throw new R.F(8);if(0>b||0>=c)throw new R.F(28);if(0===(a.flags&2097155))throw new R.F(8);if(!R.isFile(a.node.mode)&&!T(a.node.mode))throw new R.F(43);if(!a.I.na)throw new R.F(138);a.I.na(a,b,c)},la(a,b,c,d,e){if(0!==(d&2)&&0===(e&2)&&2!==(a.flags&2097155))throw new R.F(2);if(1===(a.flags&2097155))throw new R.F(2);if(!a.I.la)throw new R.F(43);if(!b)throw new R.F(28);return a.I.la(a,b,c,d,e)},ra(a,b,c,d,e){return a.I.ra?a.I.ra(a,b,c,d,e):0},Ua(a,b,c){if(!a.I.Ua)throw new R.F(59);
return a.I.Ua(a,b,c)},readFile(a,b={}){b.flags=b.flags||0;b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error(`Invalid encoding type "${b.encoding}"`);var c,d=R.open(a,b.flags);a=R.stat(a).size;var e=new Uint8Array(a);R.read(d,e,0,a,0);"utf8"===b.encoding?c=D(e):"binary"===b.encoding&&(c=e);R.close(d);return c},writeFile(a,b,c={}){c.flags=c.flags||577;a=R.open(a,c.flags,c.mode);if("string"==typeof b){var d=new Uint8Array(Lb(b)+1);b=Kb(b,d,0,d.length);R.write(a,
d,0,b,void 0,c.fb)}else if(ArrayBuffer.isView(b))R.write(a,b,0,b.byteLength,void 0,c.fb);else throw Error("Unsupported data type");R.close(a)},cwd:()=>R.Oa,chdir(a){a=X(a,{X:!0});if(null===a.node)throw new R.F(44);if(!T(a.node.mode))throw new R.F(54);var b=W(a.node,"x");if(b)throw new R.F(b);R.Oa=a.path},ac(){R.Ca=!1;for(var a=0;a<R.streams.length;a++){var b=R.streams[a];b&&R.close(b)}},Pb(a,b){try{var c=X(a,{X:!b});a=c.path}catch(g){}var d=!1,e=null;try{c=X(a,{parent:!0}),Q(a),c=X(a,{X:!b}),d=!0,
e=c.node}catch(g){}return d?e:null},Na(a,b){a="string"==typeof a?a:Y(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=P(a+"/"+c);try{R.mkdir(d)}catch(e){}a=d}}return d},Aa(a,b,c,d,e,g){var h=b;a&&(a="string"==typeof a?a:Y(a),h=b?P(a+"/"+b):a);a=tc(d,e);h=R.create(h,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}R.chmod(h,a|146);b=R.open(h,577);R.write(b,c,0,c.length,0,g);R.close(b);R.chmod(h,a)}},da(a,b,c,d){a=bc("string"==
typeof a?a:Y(a),b);b=tc(!!c,!!d);var e;(e=R.da).Ea??(e.Ea=64);e=R.ia(R.da.Ea++,0);ic(e,{open(g){g.seekable=!1},close(){d?.buffer?.length&&d(10)},read(g,h,k,n){for(var p=0,m=0;m<n;m++){try{var r=c()}catch(v){throw new R.F(29);}if(void 0===r&&0===p)throw new R.F(6);if(null===r||void 0===r)break;p++;h[k+m]=r}p&&(g.node.atime=Date.now());return p},write(g,h,k,n){for(var p=0;p<n;p++)try{d(h[k+p])}catch(m){throw new R.F(29);}n&&(g.node.mtime=g.node.ctime=Date.now());return p}});return Dc(a,b,e)},Ma(a,b,
c,d,e){class g{za=!1;aa=[];ya=void 0;Ia=0;Ha=0;get(m){if(!(m>this.length-1||0>m)){var r=m%this.chunkSize;return this.ya(m/this.chunkSize|0)[r]}}cb(m){this.ya=m}Ja(){var m=new XMLHttpRequest;m.open("HEAD",c,!1);m.send(null);if(!(200<=m.status&&300>m.status||304===m.status))throw Error("Couldn't load "+c+". Status: "+m.status);var r=Number(m.getResponseHeader("Content-length")),v,x=(v=m.getResponseHeader("Accept-Ranges"))&&"bytes"===v;m=(v=m.getResponseHeader("Content-Encoding"))&&"gzip"===v;var u=
1048576;x||(u=r);var w=this;w.cb(E=>{var M=E*u,A=(E+1)*u-1;A=Math.min(A,r-1);if("undefined"==typeof w.aa[E]){var U=w.aa;if(M>A)throw Error("invalid range ("+M+", "+A+") or no bytes requested!");if(A>r-1)throw Error("only "+r+" bytes available! programmer error!");var B=new XMLHttpRequest;B.open("GET",c,!1);r!==u&&B.setRequestHeader("Range","bytes="+M+"-"+A);B.responseType="arraybuffer";B.overrideMimeType&&B.overrideMimeType("text/plain; charset=x-user-defined");B.send(null);if(!(200<=B.status&&300>
B.status||304===B.status))throw Error("Couldn't load "+c+". Status: "+B.status);M=void 0!==B.response?new Uint8Array(B.response||[]):fc(B.responseText||"");U[E]=M}if("undefined"==typeof w.aa[E])throw Error("doXHR failed!");return w.aa[E]});if(m||!r)u=r=1,u=r=this.ya(0).length,na("LazyFiles on gzip forces download of the whole file when length is accessed");this.Ia=r;this.Ha=u;this.za=!0}get length(){this.za||this.Ja();return this.Ia}get chunkSize(){this.za||this.Ja();return this.Ha}}if("undefined"!=
typeof XMLHttpRequest){if(!ea)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new g;var k=void 0}else k=c,h=void 0;var n=Ec(a,b,d,e);h?n.J=h:k&&(n.J=null,n.url=k);Object.defineProperties(n,{M:{get:function(){return this.J.length}}});var p={};Object.keys(n.I).forEach(m=>{var r=n.I[m];p[m]=(...v)=>{Fc(n);return r(...v)}});p.read=(m,r,v,x,u)=>{Fc(n);m=m.node.J;if(u>=m.length)r=0;else{x=Math.min(m.length-u,x);if(m.slice)for(var w=
0;w<x;w++)r[v+w]=m[u+w];else for(w=0;w<x;w++)r[v+w]=m.get(u+w);r=x}return r};p.la=()=>{Fc(n);Ia();throw new R.F(48);};n.I=p;return n}},Gc=R.Na,Hc=R.Ma,Ic=R.da,Jc=Array(256),Kc=0;for(;256>Kc;++Kc)Jc[Kc]=String.fromCharCode(Kc);Sa=Jc;I=f.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};Va=f.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};
Object.assign(hb.prototype,{isAliasOf:function(a){if(!(this instanceof hb&&a instanceof hb))return!1;var b=this.G.O.K,c=this.G.L;a.G=a.G;var d=a.G.O.K;for(a=a.G.L;b.S;)c=b.ta(c),b=b.S;for(;d.S;)a=d.ta(a),d=d.S;return b===d&&c===a},clone:function(){this.G.L||Ya(this);if(this.G.sa)return this.G.count.value+=1,this;var a=eb,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.G;a=a(c.call(b,d,{G:{value:{count:e.count,pa:e.pa,sa:e.sa,L:e.L,O:e.O,R:e.R,V:e.V}}}));a.G.count.value+=1;a.G.pa=!1;return a},
["delete"](){this.G.L||Ya(this);if(this.G.pa&&!this.G.sa)throw new I("Object already scheduled for deletion");$a(this);var a=this.G;--a.count.value;0===a.count.value&&(a.R?a.V.ga(a.R):a.O.K.ga(a.L));this.G.sa||(this.G.R=void 0,this.G.L=void 0)},isDeleted:function(){return!this.G.L},deleteLater:function(){this.G.L||Ya(this);if(this.G.pa&&!this.G.sa)throw new I("Object already scheduled for deletion");gb.push(this);this.G.pa=!0;return this}});
Object.assign(tb.prototype,{pb(a){this.Xa&&(a=this.Xa(a));return a},Pa(a){this.ga?.(a)},ba:8,readValueFromPointer:sb,fromWireType:function(a){function b(){return this.wa?fb(this.K.ka,{O:this.xb,L:c,V:this,R:a}):fb(this.K.ka,{O:this,L:a})}var c=this.pb(a);if(!c)return this.Pa(a),null;var d=db(this.K,c);if(void 0!==d){if(0===d.G.count.value)return d.G.L=c,d.G.R=a,d.clone();d=d.clone();this.Pa(a);return d}d=this.K.nb(c);d=bb[d];if(!d)return b.call(this);d=this.va?d.hb:d.pointerType;var e=ab(c,this.K,
d.K);return null===e?b.call(this):this.wa?fb(d.K.ka,{O:d,L:e,V:this,R:a}):fb(d.K.ka,{O:d,L:e})}});wb=f.UnboundTypeError=((a,b)=>{var c=ib(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
O.push(0,1,void 0,1,null,1,!0,1,!1,1);f.count_emval_handles=()=>O.length/2-5-Gb.length;R.ib=sc;R.Z=Array(4096);R.N(S,{},"/");R.mkdir("/tmp");R.mkdir("/home");R.mkdir("/home/web_user");
(function(){R.mkdir("/dev");ic(R.ia(1,3),{read:()=>0,write:(d,e,g,h)=>h,T:()=>0});Dc("/dev/null",R.ia(1,3));hc(R.ia(5,0),kc);hc(R.ia(6,0),lc);Dc("/dev/tty",R.ia(5,0));Dc("/dev/tty1",R.ia(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Yb(a),b=a.byteLength);return a[--b]};R.da("/dev","random",c);R.da("/dev","urandom",c);R.mkdir("/dev/shm");R.mkdir("/dev/shm/tmp")})();
(function(){R.mkdir("/proc");var a=R.mkdir("/proc/self");R.mkdir("/proc/self/fd");R.N({N(){var b=R.createNode(a,"fd",16895,73);b.I={T:S.I.T};b.H={lookup(c,d){c=+d;var e=Ac(c);c={parent:null,N:{Wa:"fake"},H:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(R.streams.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},{},"/proc/self/fd")})();R.mb={MEMFS:S};f.FS_createPath=R.Na;f.FS_createDataFile=R.Aa;f.FS_createPreloadedFile=R.ib;f.FS_unlink=R.unlink;
f.FS_createLazyFile=R.Ma;f.FS_createDevice=R.da;S.Ra=new R.F(44);S.Ra.stack="<generic error, no stack>";
var Nc={a:(a,b,c,d)=>Ia(`Assertion failed: ${a?D(y,a):""}, at: `+[b?b?D(y,b):"":"unknown filename",c,d?d?D(y,d):"":"unknown function"]),t:()=>Ia(""),i:(a,b,c)=>{b=F(b);J(a,{name:b,fromWireType:d=>d,toWireType:function(d,e){if("bigint"!=typeof e&&"number"!=typeof e)throw new TypeError(`Cannot convert "${Ra(e)}" to ${this.name}`);"number"==typeof e&&(e=BigInt(e));return e},ba:8,readValueFromPointer:Xa(b,c,-1==b.indexOf("u")),W:null})},w:(a,b,c,d)=>{b=F(b);J(a,{name:b,fromWireType:function(e){return!!e},
toWireType:function(e,g){return g?c:d},ba:8,readValueFromPointer:function(e){return this.fromWireType(y[e])},W:null})},o:(a,b,c,d,e,g,h,k,n,p,m,r,v)=>{m=F(m);g=L(e,g);k&&=L(h,k);p&&=L(n,p);v=L(r,v);var x=lb(m);kb(x,function(){zb(`Cannot construct ${m} due to unbound types`,[d])});K([a,b,c],d?[d]:[],u=>{u=u[0];if(d){var w=u.K;var E=w.ka}else E=hb.prototype;u=ib(m,function(...B){if(Object.getPrototypeOf(this)!==M)throw new I("Use 'new' to construct "+m);if(void 0===A.ha)throw new I(m+" has no accessible constructor");
var $b=A.ha[B.length];if(void 0===$b)throw new I(`Tried to invoke ctor of ${m} with invalid number of parameters (${B.length}) - expected (${Object.keys(A.ha).toString()}) parameters instead!`);return $b.apply(this,B)});var M=Object.create(E,{constructor:{value:u}});u.prototype=M;var A=new mb(m,u,M,v,w,g,k,p);if(A.S){var U;(U=A.S).Ka??(U.Ka=[]);A.S.Ka.push(A)}w=new tb(m,A,!0,!1,!1);U=new tb(m+"*",A,!1,!1,!1);E=new tb(m+" const*",A,!1,!0,!1);bb[a]={pointerType:U,hb:E};ub(x,u);return[w,U,E]})},n:(a,
b,c,d,e,g)=>{var h=Ab(b,c);e=L(d,e);K([],[a],k=>{k=k[0];var n=`constructor ${k.name}`;void 0===k.K.ha&&(k.K.ha=[]);if(void 0!==k.K.ha[b-1])throw new I(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${k.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);k.K.ha[b-1]=()=>{zb(`Cannot construct ${k.name} due to unbound types`,h)};K([],h,p=>{p.splice(1,0,null);k.K.ha[b-1]=Eb(n,p,null,e,g);return[]});
return[]})},c:(a,b,c,d,e,g,h,k,n)=>{var p=Ab(c,d);b=F(b);b=Fb(b);g=L(e,g);K([],[a],m=>{function r(){zb(`Cannot call ${v} due to unbound types`,p)}m=m[0];var v=`${m.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);k&&m.K.yb.push(b);var x=m.K.ka,u=x[b];void 0===u||void 0===u.P&&u.className!==m.name&&u.oa===c-2?(r.oa=c-2,r.className=m.name,x[b]=r):(jb(x,b,v),x[b].P[c-2]=r);K([],p,w=>{w=Eb(v,w,m,g,h,n);void 0===x[b].P?(w.oa=c-2,x[b]=w):x[b].P[c-2]=w;return[]});return[]})},u:a=>J(a,Ib),h:(a,
b,c)=>{b=F(b);J(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,ba:8,readValueFromPointer:Jb(b,c),W:null})},g:(a,b,c,d,e,g,h)=>{var k=Ab(b,c);a=F(a);a=Fb(a);e=L(d,e);kb(a,function(){zb(`Cannot call ${a} due to unbound types`,k)},b-1);K([],k,n=>{n=[n[0],null].concat(n.slice(1));ub(a,Eb(a,n,null,e,g,h),b-1);return[]})},d:(a,b,c,d,e)=>{b=F(b);-1===e&&(e=4294967295);e=k=>k;if(0===d){var g=32-8*c;e=k=>k<<g>>>g}var h=b.includes("unsigned")?function(k,n){return n>>>0}:function(k,n){return n};J(a,{name:b,
fromWireType:e,toWireType:h,ba:8,readValueFromPointer:Xa(b,c,0!==d),W:null})},b:(a,b,c)=>{function d(g){return new e(t.buffer,z[g+4>>2],z[g>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=F(c);J(a,{name:c,fromWireType:d,ba:8,readValueFromPointer:d},{sb:!0})},v:(a,b)=>{b=F(b);J(a,{name:b,fromWireType:function(c){for(var d=z[c>>2],e=c+4,g,h=e,k=0;k<=d;++k){var n=e+k;if(k==d||0==y[n])h=h?D(y,h,n-h):"",void 0===
g?g=h:(g+=String.fromCharCode(0),g+=h),h=n+1}N(c);return g},toWireType:function(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||d instanceof Uint8Array||d instanceof Uint8ClampedArray||d instanceof Int8Array))throw new I("Cannot pass non-string to std::string");var g=e?Lb(d):d.length;var h=Lc(4+g+1),k=h+4;z[h>>2]=g;if(e)Kb(d,y,k,g+1);else if(e)for(e=0;e<g;++e){var n=d.charCodeAt(e);if(255<n)throw N(h),new I("String has UTF-16 code units that do not fit in 8 bits");
y[k+e]=n}else for(e=0;e<g;++e)y[k+e]=d[e];null!==c&&c.push(N,h);return h},ba:8,readValueFromPointer:sb,W(c){N(c)}})},e:(a,b,c)=>{c=F(c);if(2===b){var d=Nb;var e=Ob;var g=Pb;var h=k=>ta[k>>1]}else 4===b&&(d=Qb,e=Rb,g=Sb,h=k=>z[k>>2]);J(a,{name:c,fromWireType:k=>{for(var n=z[k>>2],p,m=k+4,r=0;r<=n;++r){var v=k+4+r*b;if(r==n||0==h(v))m=d(m,v-m),void 0===p?p=m:(p+=String.fromCharCode(0),p+=m),m=v+b}N(k);return p},toWireType:(k,n)=>{if("string"!=typeof n)throw new I(`Cannot pass non-string to C++ string type ${c}`);
var p=g(n),m=Lc(4+p+b);z[m>>2]=p/b;e(n,m+4,p+b);null!==k&&k.push(N,m);return m},ba:8,readValueFromPointer:sb,W(k){N(k)}})},j:a=>{J(a,Ib)},k:(a,b)=>{b=F(b);J(a,{Xb:!0,name:b,ba:0,fromWireType:()=>{},toWireType:()=>{}})},q:()=>{Pa=!1;Tb=0},l:Hb,m:a=>{9<a&&(O[a+1]+=1)},f:(a,b)=>{var c=H[a];if(void 0===c)throw a=`${"_emval_take_value"} has unknown type ${yb(a)}`,new I(a);a=c;a=a.readValueFromPointer(b);return qb(a)},r:(a,b)=>{Ub[a]&&(clearTimeout(Ub[a].id),delete Ub[a]);if(!b)return 0;var c=setTimeout(()=>
{delete Ub[a];Wb(()=>Mc(a,performance.now()))},b);Ub[a]={id:c,bc:b};return 0},s:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-pa.buffer.byteLength+65535)/65536|0;try{pa.grow(d);Aa();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},p:Vb},Z;
(async function(){function a(d){Z=d.exports;pa=Z.x;Aa();vb=Z.C;Ca.unshift(Z.y);Ha("wasm-instantiate");return Z}Ga("wasm-instantiate");var b={a:Nc};if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(d){q(`Module.instantiateWasm callback failed with error: ${d}`),ba(d)}Ja??=f.locateFile?za("thorvg.wasm")?"thorvg.wasm":f.locateFile?f.locateFile("thorvg.wasm",l):l+"thorvg.wasm":(new URL("thorvg.wasm",import.meta.url)).href;try{var c=await Ma(b);return a(c.instance)}catch(d){return ba(d),
Promise.reject(d)}})();var N=a=>(N=Z.z)(a),Lc=a=>(Lc=Z.A)(a),xb=a=>(xb=Z.B)(a),Mc=(a,b)=>(Mc=Z.D)(a,b);f.addRunDependency=Ga;f.removeRunDependency=Ha;f.FS_createPreloadedFile=sc;f.FS_unlink=a=>R.unlink(a);f.FS_createPath=Gc;f.FS_createDevice=Ic;f.FS=R;f.FS_createDataFile=(a,b,c,d,e,g)=>{R.Aa(a,b,c,d,e,g)};f.FS_createLazyFile=Hc;
function Oc(){function a(){f.calledRun=!0;if(!qa){f.noFSInit||R.Ca||qc();R.Ta=!1;Oa(Ca);aa(f);f.onRuntimeInitialized?.();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();Da.unshift(b)}Oa(Da)}}if(0<C)Fa=Oc;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Ea();Oa(Ba);0<C?Fa=Oc:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);a()},1)):a()}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();Oc();moduleRtn=ca;


  return moduleRtn;
}
);
})();
export default Module;
