var Module = (() => {
  var _scriptName = import.meta.url;
  
  return (
async function(moduleArg = {}) {
  var moduleRtn;

var f=moduleArg,aa,ba,ca=new Promise((a,b)=>{aa=a;ba=b}),da="object"==typeof window,ea="undefined"!=typeof WorkerGlobalScope,fa="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type;if(fa){const {createRequire:a}=await import("module");var require=a("/")}var ha=Object.assign({},f),ia=(a,b)=>{throw b;},l="",ja,ka;
if(fa){var fs=require("fs"),la=require("path");import.meta.url.startsWith("data:")||(l=la.dirname(require("url").fileURLToPath(import.meta.url))+"/");ka=a=>{a=ma(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=ma(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.slice(2);ia=(a,b)=>{process.exitCode=a;throw b;}}else if(da||ea)ea?l=self.location.href:"undefined"!=typeof document&&document.currentScript&&(l=document.currentScript.src),_scriptName&&(l=_scriptName),
l.startsWith("blob:")?l="":l=l.substr(0,l.replace(/[?#].*/,"").lastIndexOf("/")+1),ea&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ja=async a=>{if(ma(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();
throw Error(b.status+" : "+b.url);};var na=f.print||console.log.bind(console),q=f.printErr||console.error.bind(console);Object.assign(f,ha);ha=null;var oa=f.wasmBinary,pa,qa=!1,ra,t,y,sa,ta,ua,z,va,wa,xa,ya,za=a=>a.startsWith("data:application/octet-stream;base64,"),ma=a=>a.startsWith("file://");
function Aa(){var a=pa.buffer;f.HEAP8=t=new Int8Array(a);f.HEAP16=sa=new Int16Array(a);f.HEAPU8=y=new Uint8Array(a);f.HEAPU16=ta=new Uint16Array(a);f.HEAP32=ua=new Int32Array(a);f.HEAPU32=z=new Uint32Array(a);f.HEAPF32=va=new Float32Array(a);f.HEAPF64=ya=new Float64Array(a);f.HEAP64=wa=new BigInt64Array(a);f.HEAPU64=xa=new BigUint64Array(a)}var Ba=[],Ca=[],Da=[];function Ea(){var a=f.preRun.shift();Ba.unshift(a)}var C=0,Fa=null;function Ga(){C++;f.monitorRunDependencies?.(C)}
function Ha(){C--;f.monitorRunDependencies?.(C);if(0==C&&Fa){var a=Fa;Fa=null;a()}}function Ia(a){f.onAbort?.(a);a="Aborted("+a+")";q(a);qa=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}var Ja;async function Ka(a){if(!oa)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==Ja&&oa)a=new Uint8Array(oa);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}
async function La(a,b){try{var c=await Ka(a);return await WebAssembly.instantiate(c,b)}catch(d){q(`failed to asynchronously prepare wasm: ${d}`),Ia(d)}}async function Ma(a){var b=Ja;if(!(oa||"function"!=typeof WebAssembly.instantiateStreaming||za(b)||ma(b)||fa))try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){q(`wasm streaming compile failed: ${d}`),q("falling back to ArrayBuffer instantiation")}return La(b,a)}
class Na{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Oa=a=>{for(;0<a.length;)a.shift()(f)},Pa=f.noExitRuntime||!0,Qa="undefined"!=typeof TextDecoder?new TextDecoder:void 0,D=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Qa)return Qa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>
10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Ra=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a},Sa,E=a=>{for(var b="";y[a];)b+=Sa[y[a++]];return b},G={},H={},Ta={},I,Ua=a=>{throw new I(a);},Va,K=(a,b,c)=>{function d(k){k=c(k);if(k.length!==a.length)throw new Va("Mismatched type converter count");for(var n=0;n<a.length;++n)J(a[n],k[n])}a.forEach(k=>Ta[k]=b);var e=Array(b.length),g=[],h=0;b.forEach((k,n)=>{H.hasOwnProperty(k)?
e[n]=H[k]:(g.push(k),G.hasOwnProperty(k)||(G[k]=[]),G[k].push(()=>{e[n]=H[k];++h;h===g.length&&d(e)}))});0===g.length&&d(e)};function Wa(a,b,c={}){var d=b.name;if(!a)throw new I(`type "${d}" must have a positive integer typeid pointer`);if(H.hasOwnProperty(a)){if(c.zb)return;throw new I(`Cannot register type '${d}' twice`);}H[a]=b;delete Ta[a];G.hasOwnProperty(a)&&(b=G[a],delete G[a],b.forEach(e=>e()))}function J(a,b,c={}){return Wa(a,b,c)}
var Xa=(a,b,c)=>{switch(b){case 1:return c?d=>t[d]:d=>y[d];case 2:return c?d=>sa[d>>1]:d=>ta[d>>1];case 4:return c?d=>ua[d>>2]:d=>z[d>>2];case 8:return c?d=>wa[d>>3]:d=>xa[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Ya=a=>{throw new I(a.N.W.S.name+" instance already deleted");},Za=!1,$a=()=>{},ab=(a,b,c)=>{if(b===c)return a;if(void 0===c.Z)return null;a=ab(a,b,c.Z);return null===a?null:c.rb(a)},bb={},cb={},db=(a,b)=>{if(void 0===b)throw new I("ptr should not be undefined");
for(;a.Z;)b=a.Aa(b),a=a.Z;return cb[b]},fb=(a,b)=>{if(!b.W||!b.T)throw new Va("makeClassHandle requires ptr and ptrType");if(!!b.ba!==!!b.Y)throw new Va("Both smartPtrType and smartPtr must be specified");b.count={value:1};return eb(Object.create(a,{N:{value:b,writable:!0}}))},eb=a=>{if("undefined"===typeof FinalizationRegistry)return eb=b=>b,a;Za=new FinalizationRegistry(b=>{b=b.N;--b.count.value;0===b.count.value&&(b.Y?b.ba.na(b.Y):b.W.S.na(b.T))});eb=b=>{var c=b.N;c.Y&&Za.register(b,{N:c},b);return b};
$a=b=>{Za.unregister(b)};return eb(a)},gb=[];function hb(){}
var ib=(a,b)=>Object.defineProperty(b,"name",{value:a}),jb=(a,b,c)=>{if(void 0===a[b].X){var d=a[b];a[b]=function(...e){if(!a[b].X.hasOwnProperty(e.length))throw new I(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].X})!`);return a[b].X[e.length].apply(this,e)};a[b].X=[];a[b].X[d.va]=d}},kb=(a,b,c)=>{if(f.hasOwnProperty(a)){if(void 0===c||void 0!==f[a].X&&void 0!==f[a].X[c])throw new I(`Cannot register public name '${a}' twice`);jb(f,a,a);if(f[a].X.hasOwnProperty(c))throw new I(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
f[a].X[c]=b}else f[a]=b,f[a].va=c},lb=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function mb(a,b,c,d,e,g,h,k){this.name=a;this.constructor=b;this.ra=c;this.na=d;this.Z=e;this.ub=g;this.Aa=h;this.rb=k;this.Gb=[]}var nb=(a,b,c)=>{for(;b!==c;){if(!b.Aa)throw new I(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.Aa(a);b=b.Z}return a};
function ob(a,b){if(null===b){if(this.Ka)throw new I(`null is not a valid ${this.name}`);return 0}if(!b.N)throw new I(`Cannot pass "${Ra(b)}" as a ${this.name}`);if(!b.N.T)throw new I(`Cannot pass deleted object as a pointer of type ${this.name}`);return nb(b.N.T,b.N.W.S,this.S)}
function pb(a,b){if(null===b){if(this.Ka)throw new I(`null is not a valid ${this.name}`);if(this.Da){var c=this.Hb();null!==a&&a.push(this.na,c);return c}return 0}if(!b||!b.N)throw new I(`Cannot pass "${Ra(b)}" as a ${this.name}`);if(!b.N.T)throw new I(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.Ca&&b.N.W.Ca)throw new I(`Cannot convert argument of type ${b.N.ba?b.N.ba.name:b.N.W.name} to parameter type ${this.name}`);c=nb(b.N.T,b.N.W.S,this.S);if(this.Da){if(void 0===
b.N.Y)throw new I("Passing raw pointer to smart pointer is illegal");switch(this.Jb){case 0:if(b.N.ba===this)c=b.N.Y;else throw new I(`Cannot convert argument of type ${b.N.ba?b.N.ba.name:b.N.W.name} to parameter type ${this.name}`);break;case 1:c=b.N.Y;break;case 2:if(b.N.ba===this)c=b.N.Y;else{var d=b.clone();c=this.Ib(c,L(()=>d["delete"]()));null!==a&&a.push(this.na,c)}break;default:throw new I("Unsupporting sharing policy");}}return c}
function qb(a,b){if(null===b){if(this.Ka)throw new I(`null is not a valid ${this.name}`);return 0}if(!b.N)throw new I(`Cannot pass "${Ra(b)}" as a ${this.name}`);if(!b.N.T)throw new I(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.N.W.Ca)throw new I(`Cannot convert argument of type ${b.N.W.name} to parameter type ${this.name}`);return nb(b.N.T,b.N.W.S,this.S)}function rb(a){return this.fromWireType(z[a>>2])}
function sb(a,b,c,d,e,g,h,k,n,p,m){this.name=a;this.S=b;this.Ka=c;this.Ca=d;this.Da=e;this.Fb=g;this.Jb=h;this.eb=k;this.Hb=n;this.Ib=p;this.na=m;e||void 0!==b.Z?this.toWireType=pb:(this.toWireType=d?ob:qb,this.da=null)}
var tb=(a,b,c)=>{if(!f.hasOwnProperty(a))throw new Va("Replacing nonexistent public symbol");void 0!==f[a].X&&void 0!==c?f[a].X[c]=b:(f[a]=b,f[a].va=c)},ub,N=(a,b)=>{a=E(a);var c=ub.get(b);if("function"!=typeof c)throw new I(`unknown function pointer with signature ${a}: ${b}`);return c},vb,xb=a=>{a=wb(a);var b=E(a);O(a);return b},yb=(a,b)=>{function c(g){e[g]||H[g]||(Ta[g]?Ta[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};b.forEach(c);throw new vb(`${a}: `+d.map(xb).join([", "]));},zb=(a,b)=>{for(var c=
[],d=0;d<a;d++)c.push(z[b+4*d>>2]);return c},Ab=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function Bb(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].da)return!0;return!1}function Cb(a){var b=Function;if(!(b instanceof Function))throw new TypeError(`new_ called with constructor type ${typeof b} which is not a function`);var c=ib(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Db(a,b,c,d,e,g){var h=b.length;if(2>h)throw new I("argTypes array size mismatch! Must at least get return value and 'this' types!");var k=null!==b[1]&&null!==c,n=Bb(b);c="void"!==b[0].name;d=[a,Ua,d,e,Ab,b[0],b[1]];for(e=0;e<h-2;++e)d.push(b[e+2]);if(!n)for(e=k?1:2;e<b.length;++e)null!==b[e].da&&d.push(b[e].da);n=Bb(b);e=b.length-2;var p=[],m=["fn"];k&&m.push("thisWired");for(h=0;h<e;++h)p.push(`arg${h}`),m.push(`arg${h}Wired`);p=p.join(",");m=m.join(",");p=`return function (${p}) {\n`;n&&
(p+="var destructors = [];\n");var r=n?"destructors":"null",v="humanName throwBindingError invoker fn runDestructors retType classParam".split(" ");k&&(p+=`var thisWired = classParam['toWireType'](${r}, this);\n`);for(h=0;h<e;++h)p+=`var arg${h}Wired = argType${h}['toWireType'](${r}, arg${h});\n`,v.push(`argType${h}`);p+=(c||g?"var rv = ":"")+`invoker(${m});\n`;if(n)p+="runDestructors(destructors);\n";else for(h=k?1:2;h<b.length;++h)g=1===h?"thisWired":"arg"+(h-2)+"Wired",null!==b[h].da&&(p+=`${g}_dtor(${g});\n`,
v.push(`${g}_dtor`));c&&(p+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");let [x,u]=[v,p+"}\n"];x.push(u);b=Cb(x)(...d);return ib(a,b)}
var Eb=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?a.substr(0,b):a},Fb=[],P=[],Gb=a=>{9<a&&0===--P[a+1]&&(P[a]=void 0,Fb.push(a))},Q=a=>{if(!a)throw new I("Cannot use deleted val. handle = "+a);return P[a]},L=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Fb.pop()||P.length;P[b]=a;P[b+1]=1;return b}},Hb={name:"emscripten::val",fromWireType:a=>{var b=Q(a);Gb(a);return b},toWireType:(a,b)=>L(b),ga:8,readValueFromPointer:rb,da:null},Ib=
(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(va[c>>2])};case 8:return function(c){return this.fromWireType(ya[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Jb=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var k=a.charCodeAt(++g);h=65536+((h&1023)<<10)|k&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;
b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e},Kb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Lb="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,Mb=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&ta[c];)++c;c<<=1;if(32<c-a&&Lb)return Lb.decode(y.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=sa[a+2*d>>1];if(0==e)break;
c+=String.fromCharCode(e)}return c},Nb=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)sa[b>>1]=a.charCodeAt(e),b+=2;sa[b>>1]=0;return b-d},Ob=a=>2*a.length,Pb=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=ua[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},Qb=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);
if(55296<=g&&57343>=g){var h=a.charCodeAt(++e);g=65536+((g&1023)<<10)|h&1023}ua[b>>2]=g;b+=4;if(b+4>c)break}ua[b>>2]=0;return b-d},Rb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},Sb=0,Tb=(a,b)=>{var c=H[a];if(void 0===c)throw a=`${b} has unknown type ${xb(a)}`,new I(a);return c},Ub=(a,b,c)=>{var d=[];a=a.toWireType(d,c);d.length&&(z[b>>2]=L(d));return a},Vb=[],Wb={},Xb=a=>{var b=Wb[a];return void 0===b?E(a):b},Yb=()=>"object"==typeof globalThis?
globalThis:Function("return this")(),Zb=a=>{var b=Vb.length;Vb.push(a);return b},$b=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=Tb(z[b+4*d>>2],"parameter "+d);return c},ac={},bc=a=>{ra=a;Pa||0<Sb||(f.onExit?.(a),qa=!0);ia(a,new Na(a))},cc=a=>{if(!qa)try{if(a(),!(Pa||0<Sb))try{ra=a=ra,bc(a)}catch(b){b instanceof Na||"unwind"==b||ia(1,b)}}catch(b){b instanceof Na||"unwind"==b||ia(1,b)}},dc=()=>{if(fa){var a=require("crypto");return b=>a.randomFillSync(b)}return b=>crypto.getRandomValues(b)},ec=a=>{(ec=
dc())(a)},fc=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},gc=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=fc(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},ic=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},R=a=>
a&&a.match(/([^\/]+|\/)\/*$/)[1],jc=(a,b)=>gc(a+"/"+b),kc=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:S.cwd();if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=fc(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},lc=(a,b)=>{function c(h){for(var k=0;k<h.length&&""===h[k];k++);for(var n=h.length-1;0<=n&&""===h[n];n--);return k>n?[]:h.slice(k,n-k+1)}a=kc(a).substr(1);b=kc(b).substr(1);
a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,g=0;g<d;g++)if(a[g]!==b[g]){e=g;break}d=[];for(g=e;g<a.length;g++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},mc=[];function nc(a){var b=Array(Kb(a)+1);a=Jb(a,b,0,b.length);b.length=a;return b}var oc=[];function pc(a,b){oc[a]={input:[],output:[],ta:b};qc(a,rc)}
var rc={open(a){var b=oc[a.node.rdev];if(!b)throw new S.M(43);a.tty=b;a.seekable=!1},close(a){a.tty.ta.fsync(a.tty)},fsync(a){a.tty.ta.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.ta.Za)throw new S.M(60);for(var e=0,g=0;g<d;g++){try{var h=a.tty.ta.Za(a.tty)}catch(k){throw new S.M(29);}if(void 0===h&&0===e)throw new S.M(6);if(null===h||void 0===h)break;e++;b[c+g]=h}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.ta.Na)throw new S.M(60);try{for(var e=0;e<d;e++)a.tty.ta.Na(a.tty,
b[c+e])}catch(g){throw new S.M(29);}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},sc={Za(){a:{if(!mc.length){var a=null;if(fa){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}mc=nc(a)}a=mc.shift()}return a},Na(a,b){null===b||10===
b?(na(D(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(na(D(a.output)),a.output=[])},bc(){return{Rb:25856,Tb:5,Qb:191,Sb:35387,Pb:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},cc(){return 0},dc(){return[24,80]}},tc={Na(a,b){null===b||10===b?(q(D(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(q(D(a.output)),a.output=[])}};
function uc(a,b){var c=a.R?a.R.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.R,a.R=new Uint8Array(b),0<a.U&&a.R.set(c.subarray(0,a.U),0))}
var T={ia:null,V(){return T.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||S.isFIFO(c))throw new S.M(63);T.ia||(T.ia={dir:{node:{la:T.O.la,aa:T.O.aa,lookup:T.O.lookup,ma:T.O.ma,rename:T.O.rename,unlink:T.O.unlink,rmdir:T.O.rmdir,readdir:T.O.readdir,symlink:T.O.symlink},stream:{$:T.P.$}},file:{node:{la:T.O.la,aa:T.O.aa},stream:{$:T.P.$,read:T.P.read,write:T.P.write,ua:T.P.ua,sa:T.P.sa,ya:T.P.ya}},link:{node:{la:T.O.la,aa:T.O.aa,readlink:T.O.readlink},stream:{}},Sa:{node:{la:T.O.la,
aa:T.O.aa},stream:S.nb}});c=S.createNode(a,b,c,d);U(c.mode)?(c.O=T.ia.dir.node,c.P=T.ia.dir.stream,c.R={}):S.isFile(c.mode)?(c.O=T.ia.file.node,c.P=T.ia.file.stream,c.U=0,c.R=null):40960===(c.mode&61440)?(c.O=T.ia.link.node,c.P=T.ia.link.stream):8192===(c.mode&61440)&&(c.O=T.ia.Sa.node,c.P=T.ia.Sa.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.R[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},ac(a){return a.R?a.R.subarray?a.R.subarray(0,a.U):new Uint8Array(a.R):new Uint8Array(0)},O:{la(a){var b=
{};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;U(a.mode)?b.size=4096:S.isFile(a.mode)?b.size=a.U:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},aa(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.U!=b&&(0==b?(a.R=null,a.U=0):(c=a.R,a.R=new Uint8Array(b),
c&&a.R.set(c.subarray(0,Math.min(b,a.U))),a.U=b)))},lookup(){throw T.Ya;},ma(a,b,c,d){return T.createNode(a,b,c,d)},rename(a,b,c){try{var d=V(b,c)}catch(g){}if(d){if(U(a.mode))for(var e in d.R)throw new S.M(55);vc(d)}delete a.parent.R[a.name];b.R[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.R[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=V(a,b),d;for(d in c.R)throw new S.M(55);delete a.R[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.R)]},
symlink(a,b,c){a=T.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new S.M(28);return a.link}},P:{read(a,b,c,d,e){var g=a.node.R;if(e>=a.node.U)return 0;a=Math.min(a.node.U-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write(a,b,c,d,e,g){b.buffer===t.buffer&&(g=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.R||a.R.subarray)){if(g)return a.R=b.subarray(c,c+d),a.U=d;if(0===a.U&&0===e)return a.R=
b.slice(c,c+d),a.U=d;if(e+d<=a.U)return a.R.set(b.subarray(c,c+d),e),d}uc(a,e+d);if(a.R.subarray&&b.subarray)a.R.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.R[e+g]=b[c+g];a.U=Math.max(a.U,e+d);return d},$(a,b,c){1===c?b+=a.position:2===c&&S.isFile(a.node.mode)&&(b+=a.node.U);if(0>b)throw new S.M(28);return b},ua(a,b,c){uc(a.node,b+c);a.node.U=Math.max(a.node.U,b+c)},sa(a,b,c,d,e){if(!S.isFile(a.node.mode))throw new S.M(43);a=a.node.R;if(e&2||!a||a.buffer!==t.buffer){d=!0;Ia();e=void 0;if(!e)throw new S.M(48);
if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);t.set(a,e)}}else d=!1,e=a.byteOffset;return{T:e,Lb:d}},ya(a,b,c,d){T.P.write(a,b,0,d,c,!1);return 0}}},wc=async a=>{a=await ja(a);return new Uint8Array(a)},xc=f.preloadPlugins||[],zc=(a,b,c,d)=>{"undefined"!=typeof Browser&&yc();var e=!1;xc.forEach(g=>{!e&&g.canHandle(b)&&(g.handle(a,b,c,d),e=!0)});return e},Ac=(a,b,c,d,e,g,h,k,n,p)=>{function m(x){function u(w){p?.();k||S.Ha(a,b,w,d,e,n);g?.();Ha(v)}zc(x,
r,u,()=>{h?.();Ha(v)})||u(x)}var r=b?kc(gc(a+"/"+b)):a,v=`cp ${r}`;Ga(v);"string"==typeof c?wc(c).then(m,h):m(c)},Bc=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c};
function yc(){var a,b,c;S.Ja=!0;a??=f.stdin;b??=f.stdout;c??=f.stderr;a?S.ka("/dev","stdin",a):S.symlink("/dev/tty","/dev/stdin");b?S.ka("/dev","stdout",null,b):S.symlink("/dev/tty","/dev/stdout");c?S.ka("/dev","stderr",null,c):S.symlink("/dev/tty1","/dev/stderr");S.open("/dev/stdin",0);S.open("/dev/stdout",1);S.open("/dev/stderr",1)}function qc(a,b){S.Xa[a]={P:b}}function U(a){return 16384===(a&61440)}
function V(a,b){var c=U(a.mode)?(c=X(a,"x"))?c:a.O.lookup?0:2:54;if(c)throw new S.M(c);for(c=S.ha[Cc(a.id,b)];c;c=c.qa){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return S.lookup(a,b)}function vc(a){var b=Cc(a.parent.id,a.name);if(S.ha[b]===a)S.ha[b]=a.qa;else for(b=S.ha[b];b;){if(b.qa===a){b.qa=a.qa;break}b=b.qa}}
function Y(a,b={}){if(!a)throw new S.M(44);b.Ba??(b.Ba=!0);"/"===a.charAt(0)||(a=S.cwd()+"/"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(k=>!!k);for(var d=S.root,e="/",g=0;g<a.length;g++){var h=g===a.length-1;if(h&&b.parent)break;if("."!==a[g])if(".."===a[g])e=ic(e),d=d.parent;else{e=gc(e+"/"+a[g]);try{d=V(d,a[g])}catch(k){if(44===k?.Ia&&h&&b.Db)return{path:e};throw k;}!d.fa||h&&!b.Ba||(d=d.fa.root);if(40960===(d.mode&61440)&&(!h||b.ea)){if(!d.O.readlink)throw new S.M(52);d=d.O.readlink(d);
"/"===d.charAt(0)||(d=ic(e)+"/"+d);a=d+"/"+a.slice(g+1).join("/");continue a}}}return{path:e,node:d}}throw new S.M(32);}function Dc(a){for(var b;;){if(S.bb(a))return a=a.V.cb,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Cc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%S.ha.length}function Ec(a){var b=Cc(a.parent.id,a.name);a.qa=S.ha[b];S.ha[b]=a}function Fc(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function X(a,b){if(S.$a)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Gc(a,b){if(!U(a.mode))return 54;try{return V(a,b),20}catch(c){}return X(a,"wx")}function Hc(a,b,c){try{var d=V(a,b)}catch(e){return e.Ia}if(a=X(a,"wx"))return a;if(c){if(!U(d.mode))return 54;if(S.bb(d)||Dc(d)===S.cwd())return 10}else if(U(d.mode))return 31;return 0}function Ic(a,b){if(!a)throw new S.M(b);return a}
function Jc(a){a=S.xb(a);if(!a)throw new S.M(8);return a}function Kc(a,b=-1){a=Object.assign(new S.jb,a);if(-1==b)a:{for(b=0;b<=S.kb;b++)if(!S.streams[b])break a;throw new S.M(33);}a.fd=b;return S.streams[b]=a}function Lc(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.xa)}return b}function Mc(a,b,c){"undefined"==typeof c&&(c=b,b=438);return S.ma(a,b|8192,c)}function Nc(a,b,c,d){a="string"==typeof a?a:Dc(a);b=gc(a+"/"+b);return S.create(b,Bc(c,d))}
function Oc(a){if(!(a.Ab||a.Bb||a.link||a.R)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");try{a.R=ka(a.url),a.U=a.R.length}catch(b){throw new S.M(29);}}}
var S={root:null,xa:[],Xa:{},streams:[],Ma:1,ha:null,Va:"/",Ja:!1,$a:!0,M:class{name="ErrnoError";constructor(a){this.Ia=a}},tb:null,Ea:0,fb:{},jb:class{ja={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.ja.flags}set flags(a){this.ja.flags=a}get position(){return this.ja.position}set position(a){this.ja.position=a}},ib:class{O={};P={};fa=null;constructor(a,b,c,d){a||=this;this.parent=a;this.V=a.V;this.id=S.Ma++;this.name=b;this.mode=c;this.rdev=d;this.atime=
this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get Bb(){return U(this.mode)}get Ab(){return 8192===(this.mode&61440)}},createNode(a,b,c,d){a=new S.ib(a,b,c,d);Ec(a);return a},bb(a){return a===a.parent},isFile(a){return 32768===(a&61440)},isFIFO(a){return 4096===(a&61440)},isSocket(a){return 49152===(a&49152)},kb:4096,xb:a=>S.streams[a],Vb(a,
b=-1){a=Kc(a,b);a.P?.Ub?.(a);return a},nb:{open(a){a.P=S.vb(a.node.rdev).P;a.P.open?.(a)},$(){throw new S.M(70);}},La:a=>a>>8,ec:a=>a&255,pa:(a,b)=>a<<8|b,vb:a=>S.Xa[a],hb(a,b){function c(h){S.Ea--;return b(h)}function d(h){if(h){if(!d.sb)return d.sb=!0,c(h)}else++g>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);S.Ea++;1<S.Ea&&q(`warning: ${S.Ea} FS.syncfs operations in flight at once, probably just doing extra work`);var e=Lc(S.root.V),g=0;e.forEach(h=>{if(!h.type.hb)return d(null);h.type.hb(h,
a,d)})},V(a,b,c){var d="/"===c;if(d&&S.root)throw new S.M(10);if(!d&&c){var e=Y(c,{Ba:!1});c=e.path;e=e.node;if(e.fa)throw new S.M(10);if(!U(e.mode))throw new S.M(54);}b={type:a,Eb:b,cb:c,xa:[]};a=a.V(b);a.V=b;b.root=a;d?S.root=a:e&&(e.fa=b,e.V&&e.V.xa.push(b));return a},kc(a){a=Y(a,{Ba:!1});if(!a.node.fa)throw new S.M(28);a=a.node;var b=a.fa,c=Lc(b);Object.keys(S.ha).forEach(d=>{for(d=S.ha[d];d;){var e=d.qa;c.includes(d.V)&&vc(d);d=e}});a.fa=null;a.V.xa.splice(a.V.xa.indexOf(b),1)},lookup(a,b){return a.O.lookup(a,
b)},ma(a,b,c){var d=Y(a,{parent:!0}).node;a=R(a);if(!a)throw new S.M(28);if("."===a||".."===a)throw new S.M(20);var e=Gc(d,a);if(e)throw new S.M(e);if(!d.O.ma)throw new S.M(63);return d.O.ma(d,a,b,c)},gb(a){var b={Ob:4096,Yb:4096,blocks:1E6,Nb:5E5,Mb:5E5,files:S.Ma,Wb:S.Ma-1,Zb:42,flags:2,hc:255};a=Y(a,{ea:!0}).node;a?.O.gb&&Object.assign(b,a.O.gb(a.V.Eb.root));return b},create(a,b=438){return S.ma(a,b&4095|32768,0)},mkdir(a,b=511){return S.ma(a,b&1023|16384,0)},fc(a,b){a=a.split("/");for(var c="",
d=0;d<a.length;++d)if(a[d]){c+="/"+a[d];try{S.mkdir(c,b)}catch(e){if(20!=e.Ia)throw e;}}},symlink(a,b){if(!kc(a))throw new S.M(44);var c=Y(b,{parent:!0}).node;if(!c)throw new S.M(44);b=R(b);var d=Gc(c,b);if(d)throw new S.M(d);if(!c.O.symlink)throw new S.M(63);return c.O.symlink(c,b,a)},rename(a,b){var c=ic(a),d=ic(b),e=R(a),g=R(b);var h=Y(a,{parent:!0});var k=h.node;h=Y(b,{parent:!0});h=h.node;if(!k||!h)throw new S.M(44);if(k.V!==h.V)throw new S.M(75);var n=V(k,e);a=lc(a,d);if("."!==a.charAt(0))throw new S.M(28);
a=lc(b,c);if("."!==a.charAt(0))throw new S.M(55);try{var p=V(h,g)}catch(m){}if(n!==p){b=U(n.mode);if(e=Hc(k,e,b))throw new S.M(e);if(e=p?Hc(h,g,b):Gc(h,g))throw new S.M(e);if(!k.O.rename)throw new S.M(63);if(n.fa||p&&p.fa)throw new S.M(10);if(h!==k&&(e=X(k,"w")))throw new S.M(e);vc(n);try{k.O.rename(n,h,g),n.parent=h}catch(m){throw m;}finally{Ec(n)}}},rmdir(a){var b=Y(a,{parent:!0}).node;a=R(a);var c=V(b,a),d=Hc(b,a,!0);if(d)throw new S.M(d);if(!b.O.rmdir)throw new S.M(63);if(c.fa)throw new S.M(10);
b.O.rmdir(b,a);vc(c)},readdir(a){a=Y(a,{ea:!0}).node;return Ic(a.O.readdir,54)(a)},unlink(a){var b=Y(a,{parent:!0}).node;if(!b)throw new S.M(44);a=R(a);var c=V(b,a),d=Hc(b,a,!1);if(d)throw new S.M(d);if(!b.O.unlink)throw new S.M(63);if(c.fa)throw new S.M(10);b.O.unlink(b,a);vc(c)},readlink(a){a=Y(a).node;if(!a)throw new S.M(44);if(!a.O.readlink)throw new S.M(28);return a.O.readlink(a)},stat(a,b){a=Y(a,{ea:!b}).node;return Ic(a.O.la,63)(a)},lstat(a){return S.stat(a,!0)},chmod(a,b,c){a="string"==typeof a?
Y(a,{ea:!c}).node:a;Ic(a.O.aa,63)(a,{mode:b&4095|a.mode&-4096,ctime:Date.now(),qb:c})},lchmod(a,b){S.chmod(a,b,!0)},fchmod(a,b){a=Jc(a);S.chmod(a.node,b)},chown(a,b,c,d){a="string"==typeof a?Y(a,{ea:!d}).node:a;Ic(a.O.aa,63)(a,{timestamp:Date.now(),qb:d})},lchown(a,b,c){S.chown(a,b,c,!0)},fchown(a,b,c){a=Jc(a);S.chown(a.node,b,c)},truncate(a,b){if(0>b)throw new S.M(28);a="string"==typeof a?Y(a,{ea:!0}).node:a;if(U(a.mode))throw new S.M(31);if(!S.isFile(a.mode))throw new S.M(28);var c=X(a,"w");if(c)throw new S.M(c);
Ic(a.O.aa,63)(a,{size:b,timestamp:Date.now()})},$b(a,b){a=Jc(a);if(0===(a.flags&2097155))throw new S.M(28);S.truncate(a.node,b)},lc(a,b,c){a=Y(a,{ea:!0}).node;Ic(a.O.aa,63)(a,{atime:b,mtime:c})},open(a,b,c=438){if(""===a)throw new S.M(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");a=Y(a,{ea:!(b&131072),Db:!0});d=a.node;
a=a.path}var g=!1;if(b&64)if(d){if(b&128)throw new S.M(20);}else{if(e)throw new S.M(31);d=S.ma(a,c|511,0);g=!0}if(!d)throw new S.M(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&!U(d.mode))throw new S.M(54);if(!g&&(e=d?40960===(d.mode&61440)?32:U(d.mode)&&("r"!==Fc(b)||b&576)?31:X(d,Fc(b)):44))throw new S.M(e);b&512&&!g&&S.truncate(d,0);b&=-131713;e=Kc({node:d,path:Dc(d),flags:b,seekable:!0,position:0,P:d.P,Kb:[],error:!1});e.P.open&&e.P.open(e);g&&S.chmod(d,c&511);!f.logReadFiles||b&1||a in S.fb||
(S.fb[a]=1);return e},close(a){if(null===a.fd)throw new S.M(8);a.yb&&(a.yb=null);try{a.P.close&&a.P.close(a)}catch(b){throw b;}finally{S.streams[a.fd]=null}a.fd=null},$(a,b,c){if(null===a.fd)throw new S.M(8);if(!a.seekable||!a.P.$)throw new S.M(70);if(0!=c&&1!=c&&2!=c)throw new S.M(28);a.position=a.P.$(a,b,c);a.Kb=[];return a.position},read(a,b,c,d,e){if(0>d||0>e)throw new S.M(28);if(null===a.fd)throw new S.M(8);if(1===(a.flags&2097155))throw new S.M(8);if(U(a.node.mode))throw new S.M(31);if(!a.P.read)throw new S.M(28);
var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new S.M(70);b=a.P.read(a,b,c,d,e);g||(a.position+=b);return b},write(a,b,c,d,e,g){if(0>d||0>e)throw new S.M(28);if(null===a.fd)throw new S.M(8);if(0===(a.flags&2097155))throw new S.M(8);if(U(a.node.mode))throw new S.M(31);if(!a.P.write)throw new S.M(28);a.seekable&&a.flags&1024&&S.$(a,0,2);var h="undefined"!=typeof e;if(!h)e=a.position;else if(!a.seekable)throw new S.M(70);b=a.P.write(a,b,c,d,e,g);h||(a.position+=b);return b},
ua(a,b,c){if(null===a.fd)throw new S.M(8);if(0>b||0>=c)throw new S.M(28);if(0===(a.flags&2097155))throw new S.M(8);if(!S.isFile(a.node.mode)&&!U(a.node.mode))throw new S.M(43);if(!a.P.ua)throw new S.M(138);a.P.ua(a,b,c)},sa(a,b,c,d,e){if(0!==(d&2)&&0===(e&2)&&2!==(a.flags&2097155))throw new S.M(2);if(1===(a.flags&2097155))throw new S.M(2);if(!a.P.sa)throw new S.M(43);if(!b)throw new S.M(28);return a.P.sa(a,b,c,d,e)},ya(a,b,c,d,e){return a.P.ya?a.P.ya(a,b,c,d,e):0},ab(a,b,c){if(!a.P.ab)throw new S.M(59);
return a.P.ab(a,b,c)},readFile(a,b={}){b.flags=b.flags||0;b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error(`Invalid encoding type "${b.encoding}"`);var c,d=S.open(a,b.flags);a=S.stat(a).size;var e=new Uint8Array(a);S.read(d,e,0,a,0);"utf8"===b.encoding?c=D(e):"binary"===b.encoding&&(c=e);S.close(d);return c},writeFile(a,b,c={}){c.flags=c.flags||577;a=S.open(a,c.flags,c.mode);if("string"==typeof b){var d=new Uint8Array(Kb(b)+1);b=Jb(b,d,0,d.length);S.write(a,
d,0,b,void 0,c.mb)}else if(ArrayBuffer.isView(b))S.write(a,b,0,b.byteLength,void 0,c.mb);else throw Error("Unsupported data type");S.close(a)},cwd:()=>S.Va,chdir(a){a=Y(a,{ea:!0});if(null===a.node)throw new S.M(44);if(!U(a.node.mode))throw new S.M(54);var b=X(a.node,"x");if(b)throw new S.M(b);S.Va=a.path},ic(){S.Ja=!1;for(var a=0;a<S.streams.length;a++){var b=S.streams[a];b&&S.close(b)}},Xb(a,b){try{var c=Y(a,{ea:!b});a=c.path}catch(g){}var d=!1,e=null;try{c=Y(a,{parent:!0}),R(a),c=Y(a,{ea:!b}),d=
!0,e=c.node}catch(g){}return d?e:null},Ua(a,b){a="string"==typeof a?a:Dc(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=gc(a+"/"+c);try{S.mkdir(d)}catch(e){}a=d}}return d},Ha(a,b,c,d,e,g){var h=b;a&&(a="string"==typeof a?a:Dc(a),h=b?gc(a+"/"+b):a);a=Bc(d,e);h=S.create(h,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}S.chmod(h,a|146);b=S.open(h,577);S.write(b,c,0,c.length,0,g);S.close(b);S.chmod(h,a)}},ka(a,b,c,d){a=jc("string"==
typeof a?a:Dc(a),b);b=Bc(!!c,!!d);var e;(e=S.ka).La??(e.La=64);e=S.pa(S.ka.La++,0);qc(e,{open(g){g.seekable=!1},close(){d?.buffer?.length&&d(10)},read(g,h,k,n){for(var p=0,m=0;m<n;m++){try{var r=c()}catch(v){throw new S.M(29);}if(void 0===r&&0===p)throw new S.M(6);if(null===r||void 0===r)break;p++;h[k+m]=r}p&&(g.node.atime=Date.now());return p},write(g,h,k,n){for(var p=0;p<n;p++)try{d(h[k+p])}catch(m){throw new S.M(29);}n&&(g.node.mtime=g.node.ctime=Date.now());return p}});return Mc(a,b,e)},Ta(a,
b,c,d,e){class g{Ga=!1;ja=[];Fa=void 0;Pa=0;Oa=0;get(m){if(!(m>this.length-1||0>m)){var r=m%this.chunkSize;return this.Fa(m/this.chunkSize|0)[r]}}lb(m){this.Fa=m}Qa(){var m=new XMLHttpRequest;m.open("HEAD",c,!1);m.send(null);if(!(200<=m.status&&300>m.status||304===m.status))throw Error("Couldn't load "+c+". Status: "+m.status);var r=Number(m.getResponseHeader("Content-length")),v,x=(v=m.getResponseHeader("Accept-Ranges"))&&"bytes"===v;m=(v=m.getResponseHeader("Content-Encoding"))&&"gzip"===v;var u=
1048576;x||(u=r);var w=this;w.lb(F=>{var M=F*u,A=(F+1)*u-1;A=Math.min(A,r-1);if("undefined"==typeof w.ja[F]){var W=w.ja;if(M>A)throw Error("invalid range ("+M+", "+A+") or no bytes requested!");if(A>r-1)throw Error("only "+r+" bytes available! programmer error!");var B=new XMLHttpRequest;B.open("GET",c,!1);r!==u&&B.setRequestHeader("Range","bytes="+M+"-"+A);B.responseType="arraybuffer";B.overrideMimeType&&B.overrideMimeType("text/plain; charset=x-user-defined");B.send(null);if(!(200<=B.status&&300>
B.status||304===B.status))throw Error("Couldn't load "+c+". Status: "+B.status);M=void 0!==B.response?new Uint8Array(B.response||[]):nc(B.responseText||"");W[F]=M}if("undefined"==typeof w.ja[F])throw Error("doXHR failed!");return w.ja[F]});if(m||!r)u=r=1,u=r=this.Fa(0).length,na("LazyFiles on gzip forces download of the whole file when length is accessed");this.Pa=r;this.Oa=u;this.Ga=!0}get length(){this.Ga||this.Qa();return this.Pa}get chunkSize(){this.Ga||this.Qa();return this.Oa}}if("undefined"!=
typeof XMLHttpRequest){if(!ea)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new g;var k=void 0}else k=c,h=void 0;var n=Nc(a,b,d,e);h?n.R=h:k&&(n.R=null,n.url=k);Object.defineProperties(n,{U:{get:function(){return this.R.length}}});var p={};Object.keys(n.P).forEach(m=>{var r=n.P[m];p[m]=(...v)=>{Oc(n);return r(...v)}});p.read=(m,r,v,x,u)=>{Oc(n);m=m.node.R;if(u>=m.length)r=0;else{x=Math.min(m.length-u,x);if(m.slice)for(var w=
0;w<x;w++)r[v+w]=m[u+w];else for(w=0;w<x;w++)r[v+w]=m.get(u+w);r=x}return r};p.sa=()=>{Oc(n);Ia();throw new S.M(48);};n.P=p;return n}},Pc=S.Ua,Qc=S.Ta,Rc=S.ka,Sc=Array(256),Tc=0;for(;256>Tc;++Tc)Sc[Tc]=String.fromCharCode(Tc);Sa=Sc;I=f.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};Va=f.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};
Object.assign(hb.prototype,{isAliasOf:function(a){if(!(this instanceof hb&&a instanceof hb))return!1;var b=this.N.W.S,c=this.N.T;a.N=a.N;var d=a.N.W.S;for(a=a.N.T;b.Z;)c=b.Aa(c),b=b.Z;for(;d.Z;)a=d.Aa(a),d=d.Z;return b===d&&c===a},clone:function(){this.N.T||Ya(this);if(this.N.za)return this.N.count.value+=1,this;var a=eb,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.N;a=a(c.call(b,d,{N:{value:{count:e.count,wa:e.wa,za:e.za,T:e.T,W:e.W,Y:e.Y,ba:e.ba}}}));a.N.count.value+=1;a.N.wa=!1;return a},
["delete"](){this.N.T||Ya(this);if(this.N.wa&&!this.N.za)throw new I("Object already scheduled for deletion");$a(this);var a=this.N;--a.count.value;0===a.count.value&&(a.Y?a.ba.na(a.Y):a.W.S.na(a.T));this.N.za||(this.N.Y=void 0,this.N.T=void 0)},isDeleted:function(){return!this.N.T},deleteLater:function(){this.N.T||Ya(this);if(this.N.wa&&!this.N.za)throw new I("Object already scheduled for deletion");gb.push(this);this.N.wa=!0;return this}});
Object.assign(sb.prototype,{wb(a){this.eb&&(a=this.eb(a));return a},Wa(a){this.na?.(a)},ga:8,readValueFromPointer:rb,fromWireType:function(a){function b(){return this.Da?fb(this.S.ra,{W:this.Fb,T:c,ba:this,Y:a}):fb(this.S.ra,{W:this,T:a})}var c=this.wb(a);if(!c)return this.Wa(a),null;var d=db(this.S,c);if(void 0!==d){if(0===d.N.count.value)return d.N.T=c,d.N.Y=a,d.clone();d=d.clone();this.Wa(a);return d}d=this.S.ub(c);d=bb[d];if(!d)return b.call(this);d=this.Ca?d.ob:d.pointerType;var e=ab(c,this.S,
d.S);return null===e?b.call(this):this.Da?fb(d.S.ra,{W:d,T:e,ba:this,Y:a}):fb(d.S.ra,{W:d,T:e})}});vb=f.UnboundTypeError=((a,b)=>{var c=ib(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
P.push(0,1,void 0,1,null,1,!0,1,!1,1);f.count_emval_handles=()=>P.length/2-5-Fb.length;S.pb=Ac;S.ha=Array(4096);S.V(T,{},"/");S.mkdir("/tmp");S.mkdir("/home");S.mkdir("/home/web_user");
(function(){S.mkdir("/dev");qc(S.pa(1,3),{read:()=>0,write:(d,e,g,h)=>h,$:()=>0});Mc("/dev/null",S.pa(1,3));pc(S.pa(5,0),sc);pc(S.pa(6,0),tc);Mc("/dev/tty",S.pa(5,0));Mc("/dev/tty1",S.pa(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(ec(a),b=a.byteLength);return a[--b]};S.ka("/dev","random",c);S.ka("/dev","urandom",c);S.mkdir("/dev/shm");S.mkdir("/dev/shm/tmp")})();
(function(){S.mkdir("/proc");var a=S.mkdir("/proc/self");S.mkdir("/proc/self/fd");S.V({V(){var b=S.createNode(a,"fd",16895,73);b.P={$:T.P.$};b.O={lookup(c,d){c=+d;var e=Jc(c);c={parent:null,V:{cb:"fake"},O:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(S.streams.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},{},"/proc/self/fd")})();S.tb={MEMFS:T};f.FS_createPath=S.Ua;f.FS_createDataFile=S.Ha;f.FS_createPreloadedFile=S.pb;f.FS_unlink=S.unlink;
f.FS_createLazyFile=S.Ta;f.FS_createDevice=S.ka;T.Ya=new S.M(44);T.Ya.stack="<generic error, no stack>";
var Wc={a:(a,b,c,d)=>Ia(`Assertion failed: ${a?D(y,a):""}, at: `+[b?b?D(y,b):"":"unknown filename",c,d?d?D(y,d):"":"unknown function"]),w:()=>Ia(""),l:(a,b,c)=>{b=E(b);J(a,{name:b,fromWireType:d=>d,toWireType:function(d,e){if("bigint"!=typeof e&&"number"!=typeof e)throw new TypeError(`Cannot convert "${Ra(e)}" to ${this.name}`);"number"==typeof e&&(e=BigInt(e));return e},ga:8,readValueFromPointer:Xa(b,c,-1==b.indexOf("u")),da:null})},z:(a,b,c,d)=>{b=E(b);J(a,{name:b,fromWireType:function(e){return!!e},
toWireType:function(e,g){return g?c:d},ga:8,readValueFromPointer:function(e){return this.fromWireType(y[e])},da:null})},s:(a,b,c,d,e,g,h,k,n,p,m,r,v)=>{m=E(m);g=N(e,g);k&&=N(h,k);p&&=N(n,p);v=N(r,v);var x=lb(m);kb(x,function(){yb(`Cannot construct ${m} due to unbound types`,[d])});K([a,b,c],d?[d]:[],u=>{u=u[0];if(d){var w=u.S;var F=w.ra}else F=hb.prototype;u=ib(m,function(...B){if(Object.getPrototypeOf(this)!==M)throw new I("Use 'new' to construct "+m);if(void 0===A.oa)throw new I(m+" has no accessible constructor");
var hc=A.oa[B.length];if(void 0===hc)throw new I(`Tried to invoke ctor of ${m} with invalid number of parameters (${B.length}) - expected (${Object.keys(A.oa).toString()}) parameters instead!`);return hc.apply(this,B)});var M=Object.create(F,{constructor:{value:u}});u.prototype=M;var A=new mb(m,u,M,v,w,g,k,p);if(A.Z){var W;(W=A.Z).Ra??(W.Ra=[]);A.Z.Ra.push(A)}w=new sb(m,A,!0,!1,!1);W=new sb(m+"*",A,!1,!1,!1);F=new sb(m+" const*",A,!1,!0,!1);bb[a]={pointerType:W,ob:F};tb(x,u);return[w,W,F]})},p:(a,
b,c,d,e,g)=>{var h=zb(b,c);e=N(d,e);K([],[a],k=>{k=k[0];var n=`constructor ${k.name}`;void 0===k.S.oa&&(k.S.oa=[]);if(void 0!==k.S.oa[b-1])throw new I(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${k.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);k.S.oa[b-1]=()=>{yb(`Cannot construct ${k.name} due to unbound types`,h)};K([],h,p=>{p.splice(1,0,null);k.S.oa[b-1]=Db(n,p,null,e,g);return[]});
return[]})},c:(a,b,c,d,e,g,h,k,n)=>{var p=zb(c,d);b=E(b);b=Eb(b);g=N(e,g);K([],[a],m=>{function r(){yb(`Cannot call ${v} due to unbound types`,p)}m=m[0];var v=`${m.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);k&&m.S.Gb.push(b);var x=m.S.ra,u=x[b];void 0===u||void 0===u.X&&u.className!==m.name&&u.va===c-2?(r.va=c-2,r.className=m.name,x[b]=r):(jb(x,b,v),x[b].X[c-2]=r);K([],p,w=>{w=Db(v,w,m,g,h,n);void 0===x[b].X?(w.va=c-2,x[b]=w):x[b].X[c-2]=w;return[]});return[]})},x:a=>J(a,Hb),k:(a,
b,c)=>{b=E(b);J(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,ga:8,readValueFromPointer:Ib(b,c),da:null})},m:(a,b,c,d,e,g,h)=>{var k=zb(b,c);a=E(a);a=Eb(a);e=N(d,e);kb(a,function(){yb(`Cannot call ${a} due to unbound types`,k)},b-1);K([],k,n=>{n=[n[0],null].concat(n.slice(1));tb(a,Db(a,n,null,e,g,h),b-1);return[]})},d:(a,b,c,d,e)=>{b=E(b);-1===e&&(e=4294967295);e=k=>k;if(0===d){var g=32-8*c;e=k=>k<<g>>>g}var h=b.includes("unsigned")?function(k,n){return n>>>0}:function(k,n){return n};J(a,{name:b,
fromWireType:e,toWireType:h,ga:8,readValueFromPointer:Xa(b,c,0!==d),da:null})},b:(a,b,c)=>{function d(g){return new e(t.buffer,z[g+4>>2],z[g>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=E(c);J(a,{name:c,fromWireType:d,ga:8,readValueFromPointer:d},{zb:!0})},y:(a,b)=>{b=E(b);J(a,{name:b,fromWireType:function(c){for(var d=z[c>>2],e=c+4,g,h=e,k=0;k<=d;++k){var n=e+k;if(k==d||0==y[n])h=h?D(y,h,n-h):"",void 0===
g?g=h:(g+=String.fromCharCode(0),g+=h),h=n+1}O(c);return g},toWireType:function(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||d instanceof Uint8Array||d instanceof Uint8ClampedArray||d instanceof Int8Array))throw new I("Cannot pass non-string to std::string");var g=e?Kb(d):d.length;var h=Uc(4+g+1),k=h+4;z[h>>2]=g;if(e)Jb(d,y,k,g+1);else if(e)for(e=0;e<g;++e){var n=d.charCodeAt(e);if(255<n)throw O(h),new I("String has UTF-16 code units that do not fit in 8 bits");
y[k+e]=n}else for(e=0;e<g;++e)y[k+e]=d[e];null!==c&&c.push(O,h);return h},ga:8,readValueFromPointer:rb,da(c){O(c)}})},g:(a,b,c)=>{c=E(c);if(2===b){var d=Mb;var e=Nb;var g=Ob;var h=k=>ta[k>>1]}else 4===b&&(d=Pb,e=Qb,g=Rb,h=k=>z[k>>2]);J(a,{name:c,fromWireType:k=>{for(var n=z[k>>2],p,m=k+4,r=0;r<=n;++r){var v=k+4+r*b;if(r==n||0==h(v))m=d(m,v-m),void 0===p?p=m:(p+=String.fromCharCode(0),p+=m),m=v+b}O(k);return p},toWireType:(k,n)=>{if("string"!=typeof n)throw new I(`Cannot pass non-string to C++ string type ${c}`);
var p=g(n),m=Uc(4+p+b);z[m>>2]=p/b;e(n,m+4,p+b);null!==k&&k.push(O,m);return m},ga:8,readValueFromPointer:rb,da(k){O(k)}})},i:a=>{J(a,Hb)},A:(a,b)=>{b=E(b);J(a,{Cb:!0,name:b,ga:0,fromWireType:()=>{},toWireType:()=>{}})},t:()=>{Pa=!1;Sb=0},h:(a,b,c)=>{a=Q(a);b=Tb(b,"emval::as");return Ub(b,c,a)},o:(a,b,c,d)=>{a=Vb[a];b=Q(b);return a(null,b,c,d)},B:(a,b,c,d,e)=>{a=Vb[a];b=Q(b);c=Xb(c);return a(b,b[c],d,e)},q:Gb,C:a=>{if(0===a)return L(Yb());a=Xb(a);return L(Yb()[a])},n:(a,b,c)=>{b=$b(a,b);var d=b.shift();
a--;var e="return function (obj, func, destructorsRef, args) {\n",g=0,h=[];0===c&&h.push("obj");for(var k=["retType"],n=[d],p=0;p<a;++p)h.push("arg"+p),k.push("argType"+p),n.push(b[p]),e+=`  var arg${p} = argType${p}.readValueFromPointer(args${g?"+"+g:""});\n`,g+=b[p].ga;e+=`  var rv = ${1===c?"new func":"func.call"}(${h.join(", ")});\n`;d.Cb||(k.push("emval_returnValue"),n.push(Ub),e+="  return emval_returnValue(retType, destructorsRef, rv);\n");k.push(e+"};\n");a=Cb(k)(...n);c=`methodCaller<(${b.map(m=>
m.name).join(", ")}) => ${d.name}>`;return Zb(ib(c,a))},e:(a,b)=>{a=Q(a);b=Q(b);return L(a[b])},j:a=>{9<a&&(P[a+1]+=1)},D:a=>L(Xb(a)),E:a=>{var b=Q(a);Ab(b);Gb(a)},f:(a,b)=>{a=Tb(a,"_emval_take_value");a=a.readValueFromPointer(b);return L(a)},u:(a,b)=>{ac[a]&&(clearTimeout(ac[a].id),delete ac[a]);if(!b)return 0;var c=setTimeout(()=>{delete ac[a];cc(()=>Vc(a,performance.now()))},b);ac[a]={id:c,jc:b};return 0},v:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/
c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-pa.buffer.byteLength+65535)/65536|0;try{pa.grow(d);Aa();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},r:bc},Z;
(async function(){function a(d){Z=d.exports;pa=Z.F;Aa();ub=Z.K;Ca.unshift(Z.G);Ha("wasm-instantiate");return Z}Ga("wasm-instantiate");var b={a:Wc};if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(d){q(`Module.instantiateWasm callback failed with error: ${d}`),ba(d)}Ja??=f.locateFile?za("thorvg.wasm")?"thorvg.wasm":f.locateFile?f.locateFile("thorvg.wasm",l):l+"thorvg.wasm":(new URL("thorvg.wasm",import.meta.url)).href;try{var c=await Ma(b);return a(c.instance)}catch(d){return ba(d),
Promise.reject(d)}})();var O=a=>(O=Z.H)(a),Uc=a=>(Uc=Z.I)(a),wb=a=>(wb=Z.J)(a),Vc=(a,b)=>(Vc=Z.L)(a,b);f.addRunDependency=Ga;f.removeRunDependency=Ha;f.FS_createPreloadedFile=Ac;f.FS_unlink=a=>S.unlink(a);f.FS_createPath=Pc;f.FS_createDevice=Rc;f.FS=S;f.FS_createDataFile=(a,b,c,d,e,g)=>{S.Ha(a,b,c,d,e,g)};f.FS_createLazyFile=Qc;
function Xc(){function a(){f.calledRun=!0;if(!qa){f.noFSInit||S.Ja||yc();S.$a=!1;Oa(Ca);aa(f);f.onRuntimeInitialized?.();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();Da.unshift(b)}Oa(Da)}}if(0<C)Fa=Xc;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Ea();Oa(Ba);0<C?Fa=Xc:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);a()},1)):a()}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();Xc();moduleRtn=ca;


  return moduleRtn;
}
);
})();
export default Module;
