var Module = (() => {
  var _scriptName = import.meta.url;
  
  return (
async function(moduleArg = {}) {
  var moduleRtn;

var f=moduleArg,ba,ca,da=new Promise((a,b)=>{ba=a;ca=b}),ea="object"==typeof window,fa="undefined"!=typeof WorkerGlobalScope,ha="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type;if(ha){const {createRequire:a}=await import("module");var require=a("/")}var ia=Object.assign({},f),ja=(a,b)=>{throw b;},l="",ka,la;
if(ha){var fs=require("fs"),ma=require("path");import.meta.url.startsWith("data:")||(l=ma.dirname(require("url").fileURLToPath(import.meta.url))+"/");la=a=>{a=na(a)?new URL(a):a;return fs.readFileSync(a)};ka=async a=>{a=na(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.slice(2);ja=(a,b)=>{process.exitCode=a;throw b;}}else if(ea||fa)fa?l=self.location.href:"undefined"!=typeof document&&document.currentScript&&(l=document.currentScript.src),_scriptName&&(l=_scriptName),
l.startsWith("blob:")?l="":l=l.substr(0,l.replace(/[?#].*/,"").lastIndexOf("/")+1),fa&&(la=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ka=async a=>{if(na(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();
throw Error(b.status+" : "+b.url);};var oa=f.print||console.log.bind(console),r=f.printErr||console.error.bind(console);Object.assign(f,ia);ia=null;var pa=f.wasmBinary,qa,ra=!1,sa,t,y,z,ta,A,D,ua,va,wa,xa,ya=a=>a.startsWith("data:application/octet-stream;base64,"),na=a=>a.startsWith("file://");
function za(){var a=qa.buffer;f.HEAP8=t=new Int8Array(a);f.HEAP16=z=new Int16Array(a);f.HEAPU8=y=new Uint8Array(a);f.HEAPU16=ta=new Uint16Array(a);f.HEAP32=A=new Int32Array(a);f.HEAPU32=D=new Uint32Array(a);f.HEAPF32=ua=new Float32Array(a);f.HEAPF64=xa=new Float64Array(a);f.HEAP64=va=new BigInt64Array(a);f.HEAPU64=wa=new BigUint64Array(a)}var Aa=[],Ba=[],Ca=[];function Da(){var a=f.preRun.shift();Aa.unshift(a)}var E=0,Ea=null;function Fa(){E++;f.monitorRunDependencies?.(E)}
function Ga(){E--;f.monitorRunDependencies?.(E);if(0==E&&Ea){var a=Ea;Ea=null;a()}}function Ha(a){f.onAbort?.(a);a="Aborted("+a+")";r(a);ra=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ca(a);throw a;}var Ia;async function Ja(a){if(!pa)try{var b=await ka(a);return new Uint8Array(b)}catch{}if(a==Ia&&pa)a=new Uint8Array(pa);else if(la)a=la(a);else throw"both async and sync fetching of the wasm failed";return a}
async function Ka(a,b){try{var c=await Ja(a);return await WebAssembly.instantiate(c,b)}catch(d){r(`failed to asynchronously prepare wasm: ${d}`),Ha(d)}}async function La(a){var b=Ia;if(!(pa||"function"!=typeof WebAssembly.instantiateStreaming||ya(b)||na(b)||ha))try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){r(`wasm streaming compile failed: ${d}`),r("falling back to ArrayBuffer instantiation")}return Ka(b,a)}
class Ma{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Na=a=>{for(;0<a.length;)a.shift()(f)},Oa=f.noExitRuntime||!0,Pa="undefined"!=typeof TextDecoder?new TextDecoder:void 0,G=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Pa)return Pa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>
10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Ra=()=>{var a=A[+Qa>>2];Qa+=4;return a},Sa=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Ta=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Sa(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ua=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);
a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},H=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Va=(a,b)=>Ta(a+"/"+b),Wa=()=>{if(ha){var a=require("crypto");return b=>a.randomFillSync(b)}return b=>crypto.getRandomValues(b)},Xa=a=>{(Xa=Wa())(a)},Ya=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:I.cwd();if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Sa(b.split("/").filter(e=>!!e),
!c).join("/");return(c?"/":"")+b||"."},Za=(a,b)=>{function c(h){for(var k=0;k<h.length&&""===h[k];k++);for(var n=h.length-1;0<=n&&""===h[n];n--);return k>n?[]:h.slice(k,n-k+1)}a=Ya(a).substr(1);b=Ya(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,g=0;g<d;g++)if(a[g]!==b[g]){e=g;break}d=[];for(g=e;g<a.length;g++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},$a=[],ab=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=
2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},bb=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var k=a.charCodeAt(++g);h=65536+((h&1023)<<10)|k&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e};
function cb(a){var b=Array(ab(a)+1);a=bb(a,b,0,b.length);b.length=a;return b}var db=[];function eb(a,b){db[a]={input:[],output:[],ya:b};fb(a,gb)}
var gb={open(a){var b=db[a.node.rdev];if(!b)throw new I.X(43);a.tty=b;a.seekable=!1},close(a){a.tty.ya.fsync(a.tty)},fsync(a){a.tty.ya.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.ya.lb)throw new I.X(60);for(var e=0,g=0;g<d;g++){try{var h=a.tty.ya.lb(a.tty)}catch(k){throw new I.X(29);}if(void 0===h&&0===e)throw new I.X(6);if(null===h||void 0===h)break;e++;b[c+g]=h}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.ya.Za)throw new I.X(60);try{for(var e=0;e<d;e++)a.tty.ya.Za(a.tty,
b[c+e])}catch(g){throw new I.X(29);}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},hb={lb(){a:{if(!$a.length){var a=null;if(ha){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}$a=cb(a)}a=$a.shift()}return a},Za(a,b){null===b||10===
b?(oa(G(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(oa(G(a.output)),a.output=[])},Kb(){return{cc:25856,ec:5,bc:191,dc:35387,ac:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Lb(){return 0},Mb(){return[24,80]}},ib={Za(a,b){null===b||10===b?(r(G(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(r(G(a.output)),a.output=[])}};
function jb(a,b){var c=a.aa?a.aa.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.aa,a.aa=new Uint8Array(b),0<a.ea&&a.aa.set(c.subarray(0,a.ea),0))}
var J={ra:null,fa(){return J.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||I.isFIFO(c))throw new I.X(63);J.ra||(J.ra={dir:{node:{wa:J.Z.wa,la:J.Z.la,lookup:J.Z.lookup,xa:J.Z.xa,rename:J.Z.rename,unlink:J.Z.unlink,rmdir:J.Z.rmdir,readdir:J.Z.readdir,symlink:J.Z.symlink},stream:{ka:J.$.ka}},file:{node:{wa:J.Z.wa,la:J.Z.la},stream:{ka:J.$.ka,read:J.$.read,write:J.$.write,Fa:J.$.Fa,Ea:J.$.Ea,Ja:J.$.Ja}},link:{node:{wa:J.Z.wa,la:J.Z.la,readlink:J.Z.readlink},stream:{}},eb:{node:{wa:J.Z.wa,
la:J.Z.la},stream:I.xb}});c=I.createNode(a,b,c,d);K(c.mode)?(c.Z=J.ra.dir.node,c.$=J.ra.dir.stream,c.aa={}):I.isFile(c.mode)?(c.Z=J.ra.file.node,c.$=J.ra.file.stream,c.ea=0,c.aa=null):40960===(c.mode&61440)?(c.Z=J.ra.link.node,c.$=J.ra.link.stream):8192===(c.mode&61440)&&(c.Z=J.ra.eb.node,c.$=J.ra.eb.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.aa[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},nc(a){return a.aa?a.aa.subarray?a.aa.subarray(0,a.ea):new Uint8Array(a.aa):new Uint8Array(0)},Z:{wa(a){var b=
{};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;K(a.mode)?b.size=4096:I.isFile(a.mode)?b.size=a.ea:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},la(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.ea!=b&&(0==b?(a.aa=null,a.ea=0):(c=a.aa,a.aa=new Uint8Array(b),
c&&a.aa.set(c.subarray(0,Math.min(b,a.ea))),a.ea=b)))},lookup(){throw J.kb;},xa(a,b,c,d){return J.createNode(a,b,c,d)},rename(a,b,c){try{var d=L(b,c)}catch(g){}if(d){if(K(a.mode))for(var e in d.aa)throw new I.X(55);kb(d)}delete a.parent.aa[a.name];b.aa[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.aa[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=L(a,b),d;for(d in c.aa)throw new I.X(55);delete a.aa[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".",
"..",...Object.keys(a.aa)]},symlink(a,b,c){a=J.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new I.X(28);return a.link}},$:{read(a,b,c,d,e){var g=a.node.aa;if(e>=a.node.ea)return 0;a=Math.min(a.node.ea-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write(a,b,c,d,e,g){b.buffer===t.buffer&&(g=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.aa||a.aa.subarray)){if(g)return a.aa=b.subarray(c,
c+d),a.ea=d;if(0===a.ea&&0===e)return a.aa=b.slice(c,c+d),a.ea=d;if(e+d<=a.ea)return a.aa.set(b.subarray(c,c+d),e),d}jb(a,e+d);if(a.aa.subarray&&b.subarray)a.aa.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.aa[e+g]=b[c+g];a.ea=Math.max(a.ea,e+d);return d},ka(a,b,c){1===c?b+=a.position:2===c&&I.isFile(a.node.mode)&&(b+=a.node.ea);if(0>b)throw new I.X(28);return b},Fa(a,b,c){jb(a.node,b+c);a.node.ea=Math.max(a.node.ea,b+c)},Ea(a,b,c,d,e){if(!I.isFile(a.node.mode))throw new I.X(43);a=a.node.aa;if(e&
2||!a||a.buffer!==t.buffer){d=!0;Ha();e=void 0;if(!e)throw new I.X(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);t.set(a,e)}}else d=!1,e=a.byteOffset;return{da:e,Xb:d}},Ja(a,b,c,d){J.$.write(a,b,0,d,c,!1);return 0}}},lb=async a=>{a=await ka(a);return new Uint8Array(a)},mb=f.preloadPlugins||[],ob=(a,b,c,d)=>{"undefined"!=typeof Browser&&nb();var e=!1;mb.forEach(g=>{!e&&g.canHandle(b)&&(g.handle(a,b,c,d),e=!0)});return e},pb=(a,b,c,d,e,g,h,k,n,p)=>
{function m(x){function u(w){p?.();k||I.Sa(a,b,w,d,e,n);g?.();Ga(v)}ob(x,q,u,()=>{h?.();Ga(v)})||u(x)}var q=b?Ya(Ta(a+"/"+b)):a,v=`cp ${q}`;Fa(v);"string"==typeof c?lb(c).then(m,h):m(c)},qb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c};
function nb(){var a,b,c;I.Ua=!0;a??=f.stdin;b??=f.stdout;c??=f.stderr;a?I.ua("/dev","stdin",a):I.symlink("/dev/tty","/dev/stdin");b?I.ua("/dev","stdout",null,b):I.symlink("/dev/tty","/dev/stdout");c?I.ua("/dev","stderr",null,c):I.symlink("/dev/tty1","/dev/stderr");I.open("/dev/stdin",0);I.open("/dev/stdout",1);I.open("/dev/stderr",1)}function fb(a,b){I.jb[a]={$:b}}function K(a){return 16384===(a&61440)}
function L(a,b){var c=K(a.mode)?(c=M(a,"x"))?c:a.Z.lookup?0:2:54;if(c)throw new I.X(c);for(c=I.qa[rb(a.id,b)];c;c=c.Ca){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return I.lookup(a,b)}function kb(a){var b=rb(a.parent.id,a.name);if(I.qa[b]===a)I.qa[b]=a.Ca;else for(b=I.qa[b];b;){if(b.Ca===a){b.Ca=a.Ca;break}b=b.Ca}}
function N(a,b={}){if(!a)throw new I.X(44);b.Ma??(b.Ma=!0);"/"===a.charAt(0)||(a=I.cwd()+"/"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(k=>!!k);for(var d=I.root,e="/",g=0;g<a.length;g++){var h=g===a.length-1;if(h&&b.parent)break;if("."!==a[g])if(".."===a[g])e=Ua(e),d=d.parent;else{e=Ta(e+"/"+a[g]);try{d=L(d,a[g])}catch(k){if(44===k?.va&&h&&b.Pb)return{path:e};throw k;}!d.pa||h&&!b.Ma||(d=d.pa.root);if(40960===(d.mode&61440)&&(!h||b.oa)){if(!d.Z.readlink)throw new I.X(52);d=d.Z.readlink(d);
"/"===d.charAt(0)||(d=Ua(e)+"/"+d);a=d+"/"+a.slice(g+1).join("/");continue a}}}return{path:e,node:d}}throw new I.X(32);}function sb(a){for(var b;;){if(I.nb(a))return a=a.fa.ob,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function rb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%I.qa.length}function tb(a){var b=rb(a.parent.id,a.name);a.Ca=I.qa[b];I.qa[b]=a}function ub(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function M(a,b){if(I.mb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function vb(a,b){if(!K(a.mode))return 54;try{return L(a,b),20}catch(c){}return M(a,"wx")}function wb(a,b,c){try{var d=L(a,b)}catch(e){return e.va}if(a=M(a,"wx"))return a;if(c){if(!K(d.mode))return 54;if(I.nb(d)||sb(d)===I.cwd())return 10}else if(K(d.mode))return 31;return 0}function xb(a,b){if(!a)throw new I.X(b);return a}
function O(a){a=I.Ib(a);if(!a)throw new I.X(8);return a}function yb(a,b=-1){a=Object.assign(new I.ub,a);if(-1==b)a:{for(b=0;b<=I.vb;b++)if(!I.streams[b])break a;throw new I.X(33);}a.fd=b;return I.streams[b]=a}function zb(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.Ia)}return b}function Ab(a,b,c){"undefined"==typeof c&&(c=b,b=438);return I.xa(a,b|8192,c)}function Bb(a,b,c,d){a="string"==typeof a?a:sb(a);b=Ta(a+"/"+b);return I.create(b,qb(c,d))}
function Cb(a){if(!(a.Nb||a.Ob||a.link||a.aa)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");try{a.aa=la(a.url),a.ea=a.aa.length}catch(b){throw new I.X(29);}}}
var I={root:null,Ia:[],jb:{},streams:[],Ya:1,qa:null,hb:"/",Ua:!1,mb:!0,X:class{name="ErrnoError";constructor(a){this.va=a}},Eb:null,Pa:0,qb:{},ub:class{sa={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.sa.flags}set flags(a){this.sa.flags=a}get position(){return this.sa.position}set position(a){this.sa.position=a}},tb:class{Z={};$={};pa=null;constructor(a,b,c,d){a||=this;this.parent=a;this.fa=a.fa;this.id=I.Ya++;this.name=b;this.mode=c;this.rdev=d;this.atime=
this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get Ob(){return K(this.mode)}get Nb(){return 8192===(this.mode&61440)}},createNode(a,b,c,d){a=new I.tb(a,b,c,d);tb(a);return a},nb(a){return a===a.parent},isFile(a){return 32768===(a&61440)},isFIFO(a){return 4096===(a&61440)},isSocket(a){return 49152===(a&49152)},vb:4096,Ib:a=>I.streams[a],hc(a,
b=-1){a=yb(a,b);a.$?.fc?.(a);return a},xb:{open(a){a.$=I.Gb(a.node.rdev).$;a.$.open?.(a)},ka(){throw new I.X(70);}},Xa:a=>a>>8,pc:a=>a&255,Ba:(a,b)=>a<<8|b,Gb:a=>I.jb[a],sb(a,b){function c(h){I.Pa--;return b(h)}function d(h){if(h){if(!d.Db)return d.Db=!0,c(h)}else++g>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);I.Pa++;1<I.Pa&&r(`warning: ${I.Pa} FS.syncfs operations in flight at once, probably just doing extra work`);var e=zb(I.root.fa),g=0;e.forEach(h=>{if(!h.type.sb)return d(null);h.type.sb(h,
a,d)})},fa(a,b,c){var d="/"===c;if(d&&I.root)throw new I.X(10);if(!d&&c){var e=N(c,{Ma:!1});c=e.path;e=e.node;if(e.pa)throw new I.X(10);if(!K(e.mode))throw new I.X(54);}b={type:a,Qb:b,ob:c,Ia:[]};a=a.fa(b);a.fa=b;b.root=a;d?I.root=a:e&&(e.pa=b,e.fa&&e.fa.Ia.push(b));return a},uc(a){a=N(a,{Ma:!1});if(!a.node.pa)throw new I.X(28);a=a.node;var b=a.pa,c=zb(b);Object.keys(I.qa).forEach(d=>{for(d=I.qa[d];d;){var e=d.Ca;c.includes(d.fa)&&kb(d);d=e}});a.pa=null;a.fa.Ia.splice(a.fa.Ia.indexOf(b),1)},lookup(a,
b){return a.Z.lookup(a,b)},xa(a,b,c){var d=N(a,{parent:!0}).node;a=H(a);if(!a)throw new I.X(28);if("."===a||".."===a)throw new I.X(20);var e=vb(d,a);if(e)throw new I.X(e);if(!d.Z.xa)throw new I.X(63);return d.Z.xa(d,a,b,c)},rb(a){var b={$b:4096,kc:4096,blocks:1E6,Zb:5E5,Yb:5E5,files:I.Ya,ic:I.Ya-1,lc:42,flags:2,rc:255};a=N(a,{oa:!0}).node;a?.Z.rb&&Object.assign(b,a.Z.rb(a.fa.Qb.root));return b},create(a,b=438){return I.xa(a,b&4095|32768,0)},mkdir(a,b=511){return I.xa(a,b&1023|16384,0)},qc(a,b){a=
a.split("/");for(var c="",d=0;d<a.length;++d)if(a[d]){c+="/"+a[d];try{I.mkdir(c,b)}catch(e){if(20!=e.va)throw e;}}},symlink(a,b){if(!Ya(a))throw new I.X(44);var c=N(b,{parent:!0}).node;if(!c)throw new I.X(44);b=H(b);var d=vb(c,b);if(d)throw new I.X(d);if(!c.Z.symlink)throw new I.X(63);return c.Z.symlink(c,b,a)},rename(a,b){var c=Ua(a),d=Ua(b),e=H(a),g=H(b);var h=N(a,{parent:!0});var k=h.node;h=N(b,{parent:!0});h=h.node;if(!k||!h)throw new I.X(44);if(k.fa!==h.fa)throw new I.X(75);var n=L(k,e);a=Za(a,
d);if("."!==a.charAt(0))throw new I.X(28);a=Za(b,c);if("."!==a.charAt(0))throw new I.X(55);try{var p=L(h,g)}catch(m){}if(n!==p){b=K(n.mode);if(e=wb(k,e,b))throw new I.X(e);if(e=p?wb(h,g,b):vb(h,g))throw new I.X(e);if(!k.Z.rename)throw new I.X(63);if(n.pa||p&&p.pa)throw new I.X(10);if(h!==k&&(e=M(k,"w")))throw new I.X(e);kb(n);try{k.Z.rename(n,h,g),n.parent=h}catch(m){throw m;}finally{tb(n)}}},rmdir(a){var b=N(a,{parent:!0}).node;a=H(a);var c=L(b,a),d=wb(b,a,!0);if(d)throw new I.X(d);if(!b.Z.rmdir)throw new I.X(63);
if(c.pa)throw new I.X(10);b.Z.rmdir(b,a);kb(c)},readdir(a){a=N(a,{oa:!0}).node;return xb(a.Z.readdir,54)(a)},unlink(a){var b=N(a,{parent:!0}).node;if(!b)throw new I.X(44);a=H(a);var c=L(b,a),d=wb(b,a,!1);if(d)throw new I.X(d);if(!b.Z.unlink)throw new I.X(63);if(c.pa)throw new I.X(10);b.Z.unlink(b,a);kb(c)},readlink(a){a=N(a).node;if(!a)throw new I.X(44);if(!a.Z.readlink)throw new I.X(28);return a.Z.readlink(a)},stat(a,b){a=N(a,{oa:!b}).node;return xb(a.Z.wa,63)(a)},lstat(a){return I.stat(a,!0)},chmod(a,
b,c){a="string"==typeof a?N(a,{oa:!c}).node:a;xb(a.Z.la,63)(a,{mode:b&4095|a.mode&-4096,ctime:Date.now(),Bb:c})},lchmod(a,b){I.chmod(a,b,!0)},fchmod(a,b){a=O(a);I.chmod(a.node,b)},chown(a,b,c,d){a="string"==typeof a?N(a,{oa:!d}).node:a;xb(a.Z.la,63)(a,{timestamp:Date.now(),Bb:d})},lchown(a,b,c){I.chown(a,b,c,!0)},fchown(a,b,c){a=O(a);I.chown(a.node,b,c)},truncate(a,b){if(0>b)throw new I.X(28);a="string"==typeof a?N(a,{oa:!0}).node:a;if(K(a.mode))throw new I.X(31);if(!I.isFile(a.mode))throw new I.X(28);
var c=M(a,"w");if(c)throw new I.X(c);xb(a.Z.la,63)(a,{size:b,timestamp:Date.now()})},mc(a,b){a=O(a);if(0===(a.flags&2097155))throw new I.X(28);I.truncate(a.node,b)},vc(a,b,c){a=N(a,{oa:!0}).node;xb(a.Z.la,63)(a,{atime:b,mtime:c})},open(a,b,c=438){if(""===a)throw new I.X(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");a=
N(a,{oa:!(b&131072),Pb:!0});d=a.node;a=a.path}var g=!1;if(b&64)if(d){if(b&128)throw new I.X(20);}else{if(e)throw new I.X(31);d=I.xa(a,c|511,0);g=!0}if(!d)throw new I.X(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&!K(d.mode))throw new I.X(54);if(!g&&(e=d?40960===(d.mode&61440)?32:K(d.mode)&&("r"!==ub(b)||b&576)?31:M(d,ub(b)):44))throw new I.X(e);b&512&&!g&&I.truncate(d,0);b&=-131713;e=yb({node:d,path:sb(d),flags:b,seekable:!0,position:0,$:d.$,Wb:[],error:!1});e.$.open&&e.$.open(e);g&&I.chmod(d,
c&511);!f.logReadFiles||b&1||a in I.qb||(I.qb[a]=1);return e},close(a){if(null===a.fd)throw new I.X(8);a.Ta&&(a.Ta=null);try{a.$.close&&a.$.close(a)}catch(b){throw b;}finally{I.streams[a.fd]=null}a.fd=null},ka(a,b,c){if(null===a.fd)throw new I.X(8);if(!a.seekable||!a.$.ka)throw new I.X(70);if(0!=c&&1!=c&&2!=c)throw new I.X(28);a.position=a.$.ka(a,b,c);a.Wb=[];return a.position},read(a,b,c,d,e){if(0>d||0>e)throw new I.X(28);if(null===a.fd)throw new I.X(8);if(1===(a.flags&2097155))throw new I.X(8);
if(K(a.node.mode))throw new I.X(31);if(!a.$.read)throw new I.X(28);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new I.X(70);b=a.$.read(a,b,c,d,e);g||(a.position+=b);return b},write(a,b,c,d,e,g){if(0>d||0>e)throw new I.X(28);if(null===a.fd)throw new I.X(8);if(0===(a.flags&2097155))throw new I.X(8);if(K(a.node.mode))throw new I.X(31);if(!a.$.write)throw new I.X(28);a.seekable&&a.flags&1024&&I.ka(a,0,2);var h="undefined"!=typeof e;if(!h)e=a.position;else if(!a.seekable)throw new I.X(70);
b=a.$.write(a,b,c,d,e,g);h||(a.position+=b);return b},Fa(a,b,c){if(null===a.fd)throw new I.X(8);if(0>b||0>=c)throw new I.X(28);if(0===(a.flags&2097155))throw new I.X(8);if(!I.isFile(a.node.mode)&&!K(a.node.mode))throw new I.X(43);if(!a.$.Fa)throw new I.X(138);a.$.Fa(a,b,c)},Ea(a,b,c,d,e){if(0!==(d&2)&&0===(e&2)&&2!==(a.flags&2097155))throw new I.X(2);if(1===(a.flags&2097155))throw new I.X(2);if(!a.$.Ea)throw new I.X(43);if(!b)throw new I.X(28);return a.$.Ea(a,b,c,d,e)},Ja(a,b,c,d,e){return a.$.Ja?
a.$.Ja(a,b,c,d,e):0},Va(a,b,c){if(!a.$.Va)throw new I.X(59);return a.$.Va(a,b,c)},readFile(a,b={}){b.flags=b.flags||0;b.encoding=b.encoding||"binary";if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error(`Invalid encoding type "${b.encoding}"`);var c,d=I.open(a,b.flags);a=I.stat(a).size;var e=new Uint8Array(a);I.read(d,e,0,a,0);"utf8"===b.encoding?c=G(e):"binary"===b.encoding&&(c=e);I.close(d);return c},writeFile(a,b,c={}){c.flags=c.flags||577;a=I.open(a,c.flags,c.mode);if("string"==typeof b){var d=
new Uint8Array(ab(b)+1);b=bb(b,d,0,d.length);I.write(a,d,0,b,void 0,c.wb)}else if(ArrayBuffer.isView(b))I.write(a,b,0,b.byteLength,void 0,c.wb);else throw Error("Unsupported data type");I.close(a)},cwd:()=>I.hb,chdir(a){a=N(a,{oa:!0});if(null===a.node)throw new I.X(44);if(!K(a.node.mode))throw new I.X(54);var b=M(a.node,"x");if(b)throw new I.X(b);I.hb=a.path},sc(){I.Ua=!1;for(var a=0;a<I.streams.length;a++){var b=I.streams[a];b&&I.close(b)}},jc(a,b){try{var c=N(a,{oa:!b});a=c.path}catch(g){}var d=
!1,e=null;try{c=N(a,{parent:!0}),H(a),c=N(a,{oa:!b}),d=!0,e=c.node}catch(g){}return d?e:null},gb(a,b){a="string"==typeof a?a:sb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Ta(a+"/"+c);try{I.mkdir(d)}catch(e){}a=d}}return d},Sa(a,b,c,d,e,g){var h=b;a&&(a="string"==typeof a?a:sb(a),h=b?Ta(a+"/"+b):a);a=qb(d,e);h=I.create(h,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}I.chmod(h,a|146);b=I.open(h,577);I.write(b,c,0,c.length,
0,g);I.close(b);I.chmod(h,a)}},ua(a,b,c,d){a=Va("string"==typeof a?a:sb(a),b);b=qb(!!c,!!d);var e;(e=I.ua).Xa??(e.Xa=64);e=I.Ba(I.ua.Xa++,0);fb(e,{open(g){g.seekable=!1},close(){d?.buffer?.length&&d(10)},read(g,h,k,n){for(var p=0,m=0;m<n;m++){try{var q=c()}catch(v){throw new I.X(29);}if(void 0===q&&0===p)throw new I.X(6);if(null===q||void 0===q)break;p++;h[k+m]=q}p&&(g.node.atime=Date.now());return p},write(g,h,k,n){for(var p=0;p<n;p++)try{d(h[k+p])}catch(m){throw new I.X(29);}n&&(g.node.mtime=g.node.ctime=
Date.now());return p}});return Ab(a,b,e)},fb(a,b,c,d,e){class g{Ra=!1;sa=[];Qa=void 0;bb=0;$a=0;get(m){if(!(m>this.length-1||0>m)){var q=m%this.chunkSize;return this.Qa(m/this.chunkSize|0)[q]}}Ab(m){this.Qa=m}cb(){var m=new XMLHttpRequest;m.open("HEAD",c,!1);m.send(null);if(!(200<=m.status&&300>m.status||304===m.status))throw Error("Couldn't load "+c+". Status: "+m.status);var q=Number(m.getResponseHeader("Content-length")),v,x=(v=m.getResponseHeader("Accept-Ranges"))&&"bytes"===v;m=(v=m.getResponseHeader("Content-Encoding"))&&
"gzip"===v;var u=1048576;x||(u=q);var w=this;w.Ab(F=>{var T=F*u,B=(F+1)*u-1;B=Math.min(B,q-1);if("undefined"==typeof w.sa[F]){var aa=w.sa;if(T>B)throw Error("invalid range ("+T+", "+B+") or no bytes requested!");if(B>q-1)throw Error("only "+q+" bytes available! programmer error!");var C=new XMLHttpRequest;C.open("GET",c,!1);q!==u&&C.setRequestHeader("Range","bytes="+T+"-"+B);C.responseType="arraybuffer";C.overrideMimeType&&C.overrideMimeType("text/plain; charset=x-user-defined");C.send(null);if(!(200<=
C.status&&300>C.status||304===C.status))throw Error("Couldn't load "+c+". Status: "+C.status);T=void 0!==C.response?new Uint8Array(C.response||[]):cb(C.responseText||"");aa[F]=T}if("undefined"==typeof w.sa[F])throw Error("doXHR failed!");return w.sa[F]});if(m||!q)u=q=1,u=q=this.Qa(0).length,oa("LazyFiles on gzip forces download of the whole file when length is accessed");this.bb=q;this.$a=u;this.Ra=!0}get length(){this.Ra||this.cb();return this.bb}get chunkSize(){this.Ra||this.cb();return this.$a}}
if("undefined"!=typeof XMLHttpRequest){if(!fa)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new g;var k=void 0}else k=c,h=void 0;var n=Bb(a,b,d,e);h?n.aa=h:k&&(n.aa=null,n.url=k);Object.defineProperties(n,{ea:{get:function(){return this.aa.length}}});var p={};Object.keys(n.$).forEach(m=>{var q=n.$[m];p[m]=(...v)=>{Cb(n);return q(...v)}});p.read=(m,q,v,x,u)=>{Cb(n);m=m.node.aa;if(u>=m.length)q=0;else{x=Math.min(m.length-
u,x);if(m.slice)for(var w=0;w<x;w++)q[v+w]=m[u+w];else for(w=0;w<x;w++)q[v+w]=m.get(u+w);q=x}return q};p.Ea=()=>{Cb(n);Ha();throw new I.X(48);};n.$=p;return n}},Qa=void 0,Db=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a},Eb,P=a=>{for(var b="";y[a];)b+=Eb[y[a++]];return b},Fb={},Gb={},Hb={},Q,Ib=a=>{throw new Q(a);},Jb,Kb=(a,b,c)=>{function d(k){k=c(k);if(k.length!==a.length)throw new Jb("Mismatched type converter count");for(var n=0;n<
a.length;++n)R(a[n],k[n])}a.forEach(k=>Hb[k]=b);var e=Array(b.length),g=[],h=0;b.forEach((k,n)=>{Gb.hasOwnProperty(k)?e[n]=Gb[k]:(g.push(k),Fb.hasOwnProperty(k)||(Fb[k]=[]),Fb[k].push(()=>{e[n]=Gb[k];++h;h===g.length&&d(e)}))});0===g.length&&d(e)};
function Lb(a,b,c={}){var d=b.name;if(!a)throw new Q(`type "${d}" must have a positive integer typeid pointer`);if(Gb.hasOwnProperty(a)){if(c.Jb)return;throw new Q(`Cannot register type '${d}' twice`);}Gb[a]=b;delete Hb[a];Fb.hasOwnProperty(a)&&(b=Fb[a],delete Fb[a],b.forEach(e=>e()))}function R(a,b,c={}){return Lb(a,b,c)}
var Mb=(a,b,c)=>{switch(b){case 1:return c?d=>t[d]:d=>y[d];case 2:return c?d=>z[d>>1]:d=>ta[d>>1];case 4:return c?d=>A[d>>2]:d=>D[d>>2];case 8:return c?d=>va[d>>3]:d=>wa[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Nb=a=>{throw new Q(a.Y.ga.ba.name+" instance already deleted");},Ob=!1,Pb=()=>{},Qb=(a,b,c)=>{if(b===c)return a;if(void 0===c.ja)return null;a=Qb(a,b,c.ja);return null===a?null:c.Cb(a)},Rb={},Sb={},Tb=(a,b)=>{if(void 0===b)throw new Q("ptr should not be undefined");
for(;a.ja;)b=a.La(b),a=a.ja;return Sb[b]},Vb=(a,b)=>{if(!b.ga||!b.da)throw new Jb("makeClassHandle requires ptr and ptrType");if(!!b.ma!==!!b.ia)throw new Jb("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Ub(Object.create(a,{Y:{value:b,writable:!0}}))},Ub=a=>{if("undefined"===typeof FinalizationRegistry)return Ub=b=>b,a;Ob=new FinalizationRegistry(b=>{b=b.Y;--b.count.value;0===b.count.value&&(b.ia?b.ma.za(b.ia):b.ga.ba.za(b.da))});Ub=b=>{var c=b.Y;c.ia&&Ob.register(b,
{Y:c},b);return b};Pb=b=>{Ob.unregister(b)};return Ub(a)},Wb=[];function Xb(){}
var Yb=(a,b)=>Object.defineProperty(b,"name",{value:a}),Zb=(a,b,c)=>{if(void 0===a[b].ha){var d=a[b];a[b]=function(...e){if(!a[b].ha.hasOwnProperty(e.length))throw new Q(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].ha})!`);return a[b].ha[e.length].apply(this,e)};a[b].ha=[];a[b].ha[d.Ga]=d}},$b=(a,b,c)=>{if(f.hasOwnProperty(a)){if(void 0===c||void 0!==f[a].ha&&void 0!==f[a].ha[c])throw new Q(`Cannot register public name '${a}' twice`);Zb(f,a,a);
if(f[a].ha.hasOwnProperty(c))throw new Q(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);f[a].ha[c]=b}else f[a]=b,f[a].Ga=c},ac=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function bc(a,b,c,d,e,g,h,k){this.name=a;this.constructor=b;this.Da=c;this.za=d;this.ja=e;this.Fb=g;this.La=h;this.Cb=k;this.Sb=[]}
var cc=(a,b,c)=>{for(;b!==c;){if(!b.La)throw new Q(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.La(a);b=b.ja}return a};function dc(a,b){if(null===b){if(this.Wa)throw new Q(`null is not a valid ${this.name}`);return 0}if(!b.Y)throw new Q(`Cannot pass "${Db(b)}" as a ${this.name}`);if(!b.Y.da)throw new Q(`Cannot pass deleted object as a pointer of type ${this.name}`);return cc(b.Y.da,b.Y.ga.ba,this.ba)}
function fc(a,b){if(null===b){if(this.Wa)throw new Q(`null is not a valid ${this.name}`);if(this.Oa){var c=this.Tb();null!==a&&a.push(this.za,c);return c}return 0}if(!b||!b.Y)throw new Q(`Cannot pass "${Db(b)}" as a ${this.name}`);if(!b.Y.da)throw new Q(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.Na&&b.Y.ga.Na)throw new Q(`Cannot convert argument of type ${b.Y.ma?b.Y.ma.name:b.Y.ga.name} to parameter type ${this.name}`);c=cc(b.Y.da,b.Y.ga.ba,this.ba);if(this.Oa){if(void 0===
b.Y.ia)throw new Q("Passing raw pointer to smart pointer is illegal");switch(this.Vb){case 0:if(b.Y.ma===this)c=b.Y.ia;else throw new Q(`Cannot convert argument of type ${b.Y.ma?b.Y.ma.name:b.Y.ga.name} to parameter type ${this.name}`);break;case 1:c=b.Y.ia;break;case 2:if(b.Y.ma===this)c=b.Y.ia;else{var d=b.clone();c=this.Ub(c,gc(()=>d["delete"]()));null!==a&&a.push(this.za,c)}break;default:throw new Q("Unsupporting sharing policy");}}return c}
function hc(a,b){if(null===b){if(this.Wa)throw new Q(`null is not a valid ${this.name}`);return 0}if(!b.Y)throw new Q(`Cannot pass "${Db(b)}" as a ${this.name}`);if(!b.Y.da)throw new Q(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.Y.ga.Na)throw new Q(`Cannot convert argument of type ${b.Y.ga.name} to parameter type ${this.name}`);return cc(b.Y.da,b.Y.ga.ba,this.ba)}function ic(a){return this.fromWireType(D[a>>2])}
function jc(a,b,c,d,e,g,h,k,n,p,m){this.name=a;this.ba=b;this.Wa=c;this.Na=d;this.Oa=e;this.Rb=g;this.Vb=h;this.pb=k;this.Tb=n;this.Ub=p;this.za=m;e||void 0!==b.ja?this.toWireType=fc:(this.toWireType=d?dc:hc,this.na=null)}
var kc=(a,b,c)=>{if(!f.hasOwnProperty(a))throw new Jb("Replacing nonexistent public symbol");void 0!==f[a].ha&&void 0!==c?f[a].ha[c]=b:(f[a]=b,f[a].Ga=c)},S,lc=(a,b)=>{a=P(a);var c=S.get(b);if("function"!=typeof c)throw new Q(`unknown function pointer with signature ${a}: ${b}`);return c},mc,oc=a=>{a=nc(a);var b=P(a);U(a);return b},pc=(a,b)=>{function c(g){e[g]||Gb[g]||(Hb[g]?Hb[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};b.forEach(c);throw new mc(`${a}: `+d.map(oc).join([", "]));},qc=(a,b)=>
{for(var c=[],d=0;d<a;d++)c.push(D[b+4*d>>2]);return c},rc=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function sc(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].na)return!0;return!1}function tc(a){var b=Function;if(!(b instanceof Function))throw new TypeError(`new_ called with constructor type ${typeof b} which is not a function`);var c=Yb(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function uc(a,b,c,d,e,g){var h=b.length;if(2>h)throw new Q("argTypes array size mismatch! Must at least get return value and 'this' types!");var k=null!==b[1]&&null!==c,n=sc(b);c="void"!==b[0].name;d=[a,Ib,d,e,rc,b[0],b[1]];for(e=0;e<h-2;++e)d.push(b[e+2]);if(!n)for(e=k?1:2;e<b.length;++e)null!==b[e].na&&d.push(b[e].na);n=sc(b);e=b.length-2;var p=[],m=["fn"];k&&m.push("thisWired");for(h=0;h<e;++h)p.push(`arg${h}`),m.push(`arg${h}Wired`);p=p.join(",");m=m.join(",");p=`return function (${p}) {\n`;n&&
(p+="var destructors = [];\n");var q=n?"destructors":"null",v="humanName throwBindingError invoker fn runDestructors retType classParam".split(" ");k&&(p+=`var thisWired = classParam['toWireType'](${q}, this);\n`);for(h=0;h<e;++h)p+=`var arg${h}Wired = argType${h}['toWireType'](${q}, arg${h});\n`,v.push(`argType${h}`);p+=(c||g?"var rv = ":"")+`invoker(${m});\n`;if(n)p+="runDestructors(destructors);\n";else for(h=k?1:2;h<b.length;++h)g=1===h?"thisWired":"arg"+(h-2)+"Wired",null!==b[h].na&&(p+=`${g}_dtor(${g});\n`,
v.push(`${g}_dtor`));c&&(p+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");let [x,u]=[v,p+"}\n"];x.push(u);b=tc(x)(...d);return Yb(a,b)}
var vc=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?a.substr(0,b):a},wc=[],V=[],xc=a=>{9<a&&0===--V[a+1]&&(V[a]=void 0,wc.push(a))},gc=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=wc.pop()||V.length;V[b]=a;V[b+1]=1;return b}},yc={name:"emscripten::val",fromWireType:a=>{if(!a)throw new Q("Cannot use deleted val. handle = "+a);var b=V[a];xc(a);return b},toWireType:(a,b)=>gc(b),ta:8,readValueFromPointer:ic,na:null},zc=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(ua[c>>
2])};case 8:return function(c){return this.fromWireType(xa[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Ac="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,Bc=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&ta[c];)++c;c<<=1;if(32<c-a&&Ac)return Ac.decode(y.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=z[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},Cc=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=
0;e<c;++e)z[b>>1]=a.charCodeAt(e),b+=2;z[b>>1]=0;return b-d},Dc=a=>2*a.length,Ec=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=A[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},Fc=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=g&&57343>=g){var h=a.charCodeAt(++e);g=65536+((g&1023)<<10)|h&1023}A[b>>2]=g;b+=4;if(b+4>c)break}A[b>>2]=0;return b-d},Gc=
a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},Hc=0,Ic={},Jc=a=>{sa=a;Oa||0<Hc||(f.onExit?.(a),ra=!0);ja(a,new Ma(a))},Kc=a=>{if(!ra)try{if(a(),!(Oa||0<Hc))try{sa=a=sa,Jc(a)}catch(b){b instanceof Ma||"unwind"==b||ja(1,b)}}catch(b){b instanceof Ma||"unwind"==b||ja(1,b)}},Lc=I.gb,Mc=I.fb,Nc=I.ua;I.zb=pb;I.qa=Array(4096);I.fa(J,{},"/");I.mkdir("/tmp");I.mkdir("/home");I.mkdir("/home/web_user");
(function(){I.mkdir("/dev");fb(I.Ba(1,3),{read:()=>0,write:(d,e,g,h)=>h,ka:()=>0});Ab("/dev/null",I.Ba(1,3));eb(I.Ba(5,0),hb);eb(I.Ba(6,0),ib);Ab("/dev/tty",I.Ba(5,0));Ab("/dev/tty1",I.Ba(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Xa(a),b=a.byteLength);return a[--b]};I.ua("/dev","random",c);I.ua("/dev","urandom",c);I.mkdir("/dev/shm");I.mkdir("/dev/shm/tmp")})();
(function(){I.mkdir("/proc");var a=I.mkdir("/proc/self");I.mkdir("/proc/self/fd");I.fa({fa(){var b=I.createNode(a,"fd",16895,73);b.$={ka:J.$.ka};b.Z={lookup(c,d){c=+d;var e=O(c);c={parent:null,fa:{ob:"fake"},Z:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(I.streams.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},{},"/proc/self/fd")})();I.Eb={MEMFS:J};f.FS_createPath=I.gb;f.FS_createDataFile=I.Sa;f.FS_createPreloadedFile=I.zb;f.FS_unlink=I.unlink;
f.FS_createLazyFile=I.fb;f.FS_createDevice=I.ua;J.kb=new I.X(44);J.kb.stack="<generic error, no stack>";for(var Oc=Array(256),Pc=0;256>Pc;++Pc)Oc[Pc]=String.fromCharCode(Pc);Eb=Oc;Q=f.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};Jb=f.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};
Object.assign(Xb.prototype,{isAliasOf:function(a){if(!(this instanceof Xb&&a instanceof Xb))return!1;var b=this.Y.ga.ba,c=this.Y.da;a.Y=a.Y;var d=a.Y.ga.ba;for(a=a.Y.da;b.ja;)c=b.La(c),b=b.ja;for(;d.ja;)a=d.La(a),d=d.ja;return b===d&&c===a},clone:function(){this.Y.da||Nb(this);if(this.Y.Ka)return this.Y.count.value+=1,this;var a=Ub,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.Y;a=a(c.call(b,d,{Y:{value:{count:e.count,Ha:e.Ha,Ka:e.Ka,da:e.da,ga:e.ga,ia:e.ia,ma:e.ma}}}));a.Y.count.value+=
1;a.Y.Ha=!1;return a},["delete"](){this.Y.da||Nb(this);if(this.Y.Ha&&!this.Y.Ka)throw new Q("Object already scheduled for deletion");Pb(this);var a=this.Y;--a.count.value;0===a.count.value&&(a.ia?a.ma.za(a.ia):a.ga.ba.za(a.da));this.Y.Ka||(this.Y.ia=void 0,this.Y.da=void 0)},isDeleted:function(){return!this.Y.da},deleteLater:function(){this.Y.da||Nb(this);if(this.Y.Ha&&!this.Y.Ka)throw new Q("Object already scheduled for deletion");Wb.push(this);this.Y.Ha=!0;return this}});
Object.assign(jc.prototype,{Hb(a){this.pb&&(a=this.pb(a));return a},ib(a){this.za?.(a)},ta:8,readValueFromPointer:ic,fromWireType:function(a){function b(){return this.Oa?Vb(this.ba.Da,{ga:this.Rb,da:c,ma:this,ia:a}):Vb(this.ba.Da,{ga:this,da:a})}var c=this.Hb(a);if(!c)return this.ib(a),null;var d=Tb(this.ba,c);if(void 0!==d){if(0===d.Y.count.value)return d.Y.da=c,d.Y.ia=a,d.clone();d=d.clone();this.ib(a);return d}d=this.ba.Fb(c);d=Rb[d];if(!d)return b.call(this);d=this.Na?d.yb:d.pointerType;var e=
Qb(c,this.ba,d.ba);return null===e?b.call(this):this.Oa?Vb(d.ba.Da,{ga:d,da:e,ma:this,ia:a}):Vb(d.ba.Da,{ga:d,da:e})}});mc=f.UnboundTypeError=((a,b)=>{var c=Yb(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
V.push(0,1,void 0,1,null,1,!0,1,!1,1);f.count_emval_handles=()=>V.length/2-5-wc.length;
var ad={c:(a,b,c,d)=>Ha(`Assertion failed: ${a?G(y,a):""}, at: `+[b?b?G(y,b):"":"unknown filename",c,d?d?G(y,d):"":"unknown function"]),H:function(a,b,c){Qa=c;try{var d=O(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.ya.Kb){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Ra();A[e>>2]=25856;A[e+4>>2]=5;A[e+8>>2]=191;A[e+12>>2]=35387;for(var g=0;32>g;g++)t[e+g+17]=a[g]||0}return 0;case 21510:case 21511:case 21512:return d.tty?
0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.ya.Lb)for(e=Ra(),a=[],g=0;32>g;g++)a.push(t[e+g+17]);return 0;case 21519:if(!d.tty)return-59;e=Ra();return A[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:return e=Ra(),I.Va(d,b,e);case 21523:if(!d.tty)return-59;d.tty.ya.Mb&&(g=[24,80],e=Ra(),z[e>>1]=g[0],z[e+2>>1]=g[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(h){if("undefined"==typeof I||"ErrnoError"!==h.name)throw h;return-h.va}},
I:function(a,b,c,d){Qa=d;try{b=b?G(y,b):"";var e=b;if("/"===e.charAt(0))b=e;else{var g=-100===a?I.cwd():O(a).path;if(0==e.length)throw new I.X(44);b=g+"/"+e}var h=d?Ra():0;return I.open(b,c,h).fd}catch(k){if("undefined"==typeof I||"ErrnoError"!==k.name)throw k;return-k.va}},J:()=>Ha(""),s:(a,b,c)=>{b=P(b);R(a,{name:b,fromWireType:d=>d,toWireType:function(d,e){if("bigint"!=typeof e&&"number"!=typeof e)throw new TypeError(`Cannot convert "${Db(e)}" to ${this.name}`);"number"==typeof e&&(e=BigInt(e));
return e},ta:8,readValueFromPointer:Mb(b,c,-1==b.indexOf("u")),na:null})},M:(a,b,c,d)=>{b=P(b);R(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,g){return g?c:d},ta:8,readValueFromPointer:function(e){return this.fromWireType(y[e])},na:null})},y:(a,b,c,d,e,g,h,k,n,p,m,q,v)=>{m=P(m);g=lc(e,g);k&&=lc(h,k);p&&=lc(n,p);v=lc(q,v);var x=ac(m);$b(x,function(){pc(`Cannot construct ${m} due to unbound types`,[d])});Kb([a,b,c],d?[d]:[],u=>{u=u[0];if(d){var w=u.ba;var F=w.Da}else F=Xb.prototype;
u=Yb(m,function(...C){if(Object.getPrototypeOf(this)!==T)throw new Q("Use 'new' to construct "+m);if(void 0===B.Aa)throw new Q(m+" has no accessible constructor");var ec=B.Aa[C.length];if(void 0===ec)throw new Q(`Tried to invoke ctor of ${m} with invalid number of parameters (${C.length}) - expected (${Object.keys(B.Aa).toString()}) parameters instead!`);return ec.apply(this,C)});var T=Object.create(F,{constructor:{value:u}});u.prototype=T;var B=new bc(m,u,T,v,w,g,k,p);if(B.ja){var aa;(aa=B.ja).ab??
(aa.ab=[]);B.ja.ab.push(B)}w=new jc(m,B,!0,!1,!1);aa=new jc(m+"*",B,!1,!1,!1);F=new jc(m+" const*",B,!1,!0,!1);Rb[a]={pointerType:aa,yb:F};kc(x,u);return[w,aa,F]})},x:(a,b,c,d,e,g)=>{var h=qc(b,c);e=lc(d,e);Kb([],[a],k=>{k=k[0];var n=`constructor ${k.name}`;void 0===k.ba.Aa&&(k.ba.Aa=[]);if(void 0!==k.ba.Aa[b-1])throw new Q(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${k.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);
k.ba.Aa[b-1]=()=>{pc(`Cannot construct ${k.name} due to unbound types`,h)};Kb([],h,p=>{p.splice(1,0,null);k.ba.Aa[b-1]=uc(n,p,null,e,g);return[]});return[]})},h:(a,b,c,d,e,g,h,k,n)=>{var p=qc(c,d);b=P(b);b=vc(b);g=lc(e,g);Kb([],[a],m=>{function q(){pc(`Cannot call ${v} due to unbound types`,p)}m=m[0];var v=`${m.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);k&&m.ba.Sb.push(b);var x=m.ba.Da,u=x[b];void 0===u||void 0===u.ha&&u.className!==m.name&&u.Ga===c-2?(q.Ga=c-2,q.className=m.name,
x[b]=q):(Zb(x,b,v),x[b].ha[c-2]=q);Kb([],p,w=>{w=uc(v,w,m,g,h,n);void 0===x[b].ha?(w.Ga=c-2,x[b]=w):x[b].ha[c-2]=w;return[]});return[]})},K:a=>R(a,yc),r:(a,b,c)=>{b=P(b);R(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,ta:8,readValueFromPointer:zc(b,c),na:null})},q:(a,b,c,d,e,g,h)=>{var k=qc(b,c);a=P(a);a=vc(a);e=lc(d,e);$b(a,function(){pc(`Cannot call ${a} due to unbound types`,k)},b-1);Kb([],k,n=>{n=[n[0],null].concat(n.slice(1));kc(a,uc(a,n,null,e,g,h),b-1);return[]})},j:(a,b,c,d,e)=>{b=P(b);
-1===e&&(e=4294967295);e=k=>k;if(0===d){var g=32-8*c;e=k=>k<<g>>>g}var h=b.includes("unsigned")?function(k,n){return n>>>0}:function(k,n){return n};R(a,{name:b,fromWireType:e,toWireType:h,ta:8,readValueFromPointer:Mb(b,c,0!==d),na:null})},g:(a,b,c)=>{function d(g){return new e(t.buffer,D[g+4>>2],D[g>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=P(c);R(a,{name:c,fromWireType:d,ta:8,readValueFromPointer:d},
{Jb:!0})},L:(a,b)=>{b=P(b);R(a,{name:b,fromWireType:function(c){for(var d=D[c>>2],e=c+4,g,h=e,k=0;k<=d;++k){var n=e+k;if(k==d||0==y[n])h=h?G(y,h,n-h):"",void 0===g?g=h:(g+=String.fromCharCode(0),g+=h),h=n+1}U(c);return g},toWireType:function(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||d instanceof Uint8Array||d instanceof Uint8ClampedArray||d instanceof Int8Array))throw new Q("Cannot pass non-string to std::string");var g=e?ab(d):d.length;var h=Qc(4+g+1),
k=h+4;D[h>>2]=g;if(e)bb(d,y,k,g+1);else if(e)for(e=0;e<g;++e){var n=d.charCodeAt(e);if(255<n)throw U(h),new Q("String has UTF-16 code units that do not fit in 8 bits");y[k+e]=n}else for(e=0;e<g;++e)y[k+e]=d[e];null!==c&&c.push(U,h);return h},ta:8,readValueFromPointer:ic,na(c){U(c)}})},l:(a,b,c)=>{c=P(c);if(2===b){var d=Bc;var e=Cc;var g=Dc;var h=k=>ta[k>>1]}else 4===b&&(d=Ec,e=Fc,g=Gc,h=k=>D[k>>2]);R(a,{name:c,fromWireType:k=>{for(var n=D[k>>2],p,m=k+4,q=0;q<=n;++q){var v=k+4+q*b;if(q==n||0==h(v))m=
d(m,v-m),void 0===p?p=m:(p+=String.fromCharCode(0),p+=m),m=v+b}U(k);return p},toWireType:(k,n)=>{if("string"!=typeof n)throw new Q(`Cannot pass non-string to C++ string type ${c}`);var p=g(n),m=Qc(4+p+b);D[m>>2]=p/b;e(n,m+4,p+b);null!==k&&k.push(U,m);return m},ta:8,readValueFromPointer:ic,na(k){U(k)}})},t:a=>{R(a,yc)},u:(a,b)=>{b=P(b);R(a,{oc:!0,name:b,ta:0,fromWireType:()=>{},toWireType:()=>{}})},B:()=>{Oa=!1;Hc=0},z:()=>{throw Infinity;},v:xc,w:a=>{9<a&&(V[a+1]+=1)},m:(a,b)=>{var c=Gb[a];if(void 0===
c)throw a=`${"_emval_take_value"} has unknown type ${oc(a)}`,new Q(a);a=c;a=a.readValueFromPointer(b);return gc(a)},C:(a,b)=>{Ic[a]&&(clearTimeout(Ic[a].id),delete Ic[a]);if(!b)return 0;var c=setTimeout(()=>{delete Ic[a];Kc(()=>Rc(a,performance.now()))},b);Ic[a]={id:c,tc:b};return 0},D:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-qa.buffer.byteLength+65535)/65536|
0;try{qa.grow(d);za();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},p:function(a){try{var b=O(a);I.close(b);return 0}catch(c){if("undefined"==typeof I||"ErrnoError"!==c.name)throw c;return c.va}},G:function(a,b,c,d){try{a:{var e=O(a);a=b;for(var g,h=b=0;h<c;h++){var k=D[a>>2],n=D[a+4>>2];a+=8;var p=I.read(e,t,k,n,g);if(0>p){var m=-1;break a}b+=p;if(p<n)break;"undefined"!=typeof g&&(g+=p)}m=b}D[d>>2]=m;return 0}catch(q){if("undefined"==typeof I||"ErrnoError"!==q.name)throw q;return q.va}},
E:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=O(a);I.ka(e,b,c);va[d>>3]=BigInt(e.position);e.Ta&&0===b&&0===c&&(e.Ta=null);return 0}catch(g){if("undefined"==typeof I||"ErrnoError"!==g.name)throw g;return g.va}},F:function(a,b,c,d){try{a:{var e=O(a);a=b;for(var g,h=b=0;h<c;h++){var k=D[a>>2],n=D[a+4>>2];a+=8;var p=I.write(e,t,k,n,g);if(0>p){var m=-1;break a}b+=p;if(p<n)break;"undefined"!=typeof g&&(g+=p)}m=b}D[d>>2]=m;return 0}catch(q){if("undefined"==
typeof I||"ErrnoError"!==q.name)throw q;return q.va}},i:Sc,e:Tc,d:Uc,o:Vc,n:Wc,a:Xc,b:Yc,f:Zc,k:$c,A:Jc},W;
(async function(){function a(d){W=d.exports;qa=W.N;za();S=W.S;Ba.unshift(W.O);Ga("wasm-instantiate");return W}Fa("wasm-instantiate");var b={a:ad};if(f.instantiateWasm)try{return f.instantiateWasm(b,a)}catch(d){r(`Module.instantiateWasm callback failed with error: ${d}`),ca(d)}Ia??=f.locateFile?ya("thorvg.wasm")?"thorvg.wasm":f.locateFile?f.locateFile("thorvg.wasm",l):l+"thorvg.wasm":(new URL("thorvg.wasm",import.meta.url)).href;try{var c=await La(b);return a(c.instance)}catch(d){return ca(d),
Promise.reject(d)}})();var U=a=>(U=W.P)(a),Qc=a=>(Qc=W.Q)(a),nc=a=>(nc=W.R)(a),Rc=(a,b)=>(Rc=W.T)(a,b),X=(a,b)=>(X=W.U)(a,b),Y=a=>(Y=W.V)(a),Z=()=>(Z=W.W)();function Vc(a,b,c,d,e,g){var h=Z();try{return S.get(a)(b,c,d,e,g)}catch(k){Y(h);if(k!==k+0)throw k;X(1,0)}}function Xc(a,b){var c=Z();try{S.get(a)(b)}catch(d){Y(c);if(d!==d+0)throw d;X(1,0)}}function Tc(a,b,c){var d=Z();try{return S.get(a)(b,c)}catch(e){Y(d);if(e!==e+0)throw e;X(1,0)}}
function Yc(a,b,c){var d=Z();try{S.get(a)(b,c)}catch(e){Y(d);if(e!==e+0)throw e;X(1,0)}}function Zc(a,b,c,d){var e=Z();try{S.get(a)(b,c,d)}catch(g){Y(e);if(g!==g+0)throw g;X(1,0)}}function Sc(a,b){var c=Z();try{return S.get(a)(b)}catch(d){Y(c);if(d!==d+0)throw d;X(1,0)}}function Wc(a){var b=Z();try{S.get(a)()}catch(c){Y(b);if(c!==c+0)throw c;X(1,0)}}function Uc(a,b,c,d){var e=Z();try{return S.get(a)(b,c,d)}catch(g){Y(e);if(g!==g+0)throw g;X(1,0)}}
function $c(a,b,c,d,e){var g=Z();try{S.get(a)(b,c,d,e)}catch(h){Y(g);if(h!==h+0)throw h;X(1,0)}}f.addRunDependency=Fa;f.removeRunDependency=Ga;f.FS_createPreloadedFile=pb;f.FS_unlink=a=>I.unlink(a);f.FS_createPath=Lc;f.FS_createDevice=Nc;f.FS=I;f.FS_createDataFile=(a,b,c,d,e,g)=>{I.Sa(a,b,c,d,e,g)};f.FS_createLazyFile=Mc;
function bd(){function a(){f.calledRun=!0;if(!ra){f.noFSInit||I.Ua||nb();I.mb=!1;Na(Ba);ba(f);f.onRuntimeInitialized?.();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();Ca.unshift(b)}Na(Ca)}}if(0<E)Ea=bd;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Da();Na(Aa);0<E?Ea=bd:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);a()},1)):a()}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();bd();moduleRtn=da;


  return moduleRtn;
}
);
})();
export default Module;
